-- Nationality master (owner decision 2026-10-03): a fixed, standard list replaces the
-- free-text nationality. Codes are ISO 3166-1 alpha-3 (as on passports); the list holds the
-- 193 UN member states, the Holy See and Palestine, Kosovo (XKX, the passport code), Taiwan,
-- Hong Kong, Macau, and ICAO's XXA for stateless persons. A later change comes with a release.

-- CreateTable
CREATE TABLE "nationalities" (
    "code" VARCHAR(3) NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "name_ar" VARCHAR(80),
    "country_name" VARCHAR(80) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "nationalities_pkey" PRIMARY KEY ("code")
);

-- CreateIndex
CREATE UNIQUE INDEX "nationalities_name_key" ON "nationalities"("name");

INSERT INTO "nationalities" ("code", "name", "name_ar", "country_name", "sort_order", "updated_at") VALUES
    ('AFG', 'Afghan', 'أفغاني', 'Afghanistan', 1, CURRENT_TIMESTAMP),
    ('ALB', 'Albanian', 'ألباني', 'Albania', 2, CURRENT_TIMESTAMP),
    ('DZA', 'Algerian', 'جزائري', 'Algeria', 3, CURRENT_TIMESTAMP),
    ('USA', 'American', 'أمريكي', 'United States of America', 4, CURRENT_TIMESTAMP),
    ('AND', 'Andorran', 'أندوري', 'Andorra', 5, CURRENT_TIMESTAMP),
    ('AGO', 'Angolan', 'أنغولي', 'Angola', 6, CURRENT_TIMESTAMP),
    ('ATG', 'Antiguan or Barbudan', 'أنتيغوي', 'Antigua and Barbuda', 7, CURRENT_TIMESTAMP),
    ('ARG', 'Argentine', 'أرجنتيني', 'Argentina', 8, CURRENT_TIMESTAMP),
    ('ARM', 'Armenian', 'أرميني', 'Armenia', 9, CURRENT_TIMESTAMP),
    ('AUS', 'Australian', 'أسترالي', 'Australia', 10, CURRENT_TIMESTAMP),
    ('AUT', 'Austrian', 'نمساوي', 'Austria', 11, CURRENT_TIMESTAMP),
    ('AZE', 'Azerbaijani', 'أذربيجاني', 'Azerbaijan', 12, CURRENT_TIMESTAMP),
    ('BHS', 'Bahamian', 'باهامي', 'Bahamas', 13, CURRENT_TIMESTAMP),
    ('BHR', 'Bahraini', 'بحريني', 'Bahrain', 14, CURRENT_TIMESTAMP),
    ('BGD', 'Bangladeshi', 'بنغلاديشي', 'Bangladesh', 15, CURRENT_TIMESTAMP),
    ('BRB', 'Barbadian', 'بربادوسي', 'Barbados', 16, CURRENT_TIMESTAMP),
    ('BLR', 'Belarusian', 'بيلاروسي', 'Belarus', 17, CURRENT_TIMESTAMP),
    ('BEL', 'Belgian', 'بلجيكي', 'Belgium', 18, CURRENT_TIMESTAMP),
    ('BLZ', 'Belizean', 'بليزي', 'Belize', 19, CURRENT_TIMESTAMP),
    ('BEN', 'Beninese', 'بنيني', 'Benin', 20, CURRENT_TIMESTAMP),
    ('BTN', 'Bhutanese', 'بوتاني', 'Bhutan', 21, CURRENT_TIMESTAMP),
    ('GNB', 'Bissau-Guinean', 'غيني بيساوي', 'Guinea-Bissau', 22, CURRENT_TIMESTAMP),
    ('BOL', 'Bolivian', 'بوليفي', 'Bolivia', 23, CURRENT_TIMESTAMP),
    ('BIH', 'Bosnian', 'بوسني', 'Bosnia and Herzegovina', 24, CURRENT_TIMESTAMP),
    ('BRA', 'Brazilian', 'برازيلي', 'Brazil', 25, CURRENT_TIMESTAMP),
    ('GBR', 'British', 'بريطاني', 'United Kingdom', 26, CURRENT_TIMESTAMP),
    ('BRN', 'Bruneian', 'بروناوي', 'Brunei Darussalam', 27, CURRENT_TIMESTAMP),
    ('BGR', 'Bulgarian', 'بلغاري', 'Bulgaria', 28, CURRENT_TIMESTAMP),
    ('BFA', 'Burkinabe', 'بوركيني', 'Burkina Faso', 29, CURRENT_TIMESTAMP),
    ('MMR', 'Burmese (Myanmar)', 'ميانماري', 'Myanmar', 30, CURRENT_TIMESTAMP),
    ('BDI', 'Burundian', 'بوروندي', 'Burundi', 31, CURRENT_TIMESTAMP),
    ('CPV', 'Cabo Verdean', 'رأس أخضري', 'Cabo Verde', 32, CURRENT_TIMESTAMP),
    ('KHM', 'Cambodian', 'كمبودي', 'Cambodia', 33, CURRENT_TIMESTAMP),
    ('CMR', 'Cameroonian', 'كاميروني', 'Cameroon', 34, CURRENT_TIMESTAMP),
    ('CAN', 'Canadian', 'كندي', 'Canada', 35, CURRENT_TIMESTAMP),
    ('CAF', 'Central African', 'أفريقي أوسطي', 'Central African Republic', 36, CURRENT_TIMESTAMP),
    ('TCD', 'Chadian', 'تشادي', 'Chad', 37, CURRENT_TIMESTAMP),
    ('CHL', 'Chilean', 'تشيلي', 'Chile', 38, CURRENT_TIMESTAMP),
    ('CHN', 'Chinese', 'صيني', 'China', 39, CURRENT_TIMESTAMP),
    ('COL', 'Colombian', 'كولومبي', 'Colombia', 40, CURRENT_TIMESTAMP),
    ('COM', 'Comorian', 'قمري', 'Comoros', 41, CURRENT_TIMESTAMP),
    ('COD', 'Congolese (DR Congo)', 'كونغولي (الكونغو الديمقراطية)', 'Congo, Democratic Republic of the', 42, CURRENT_TIMESTAMP),
    ('COG', 'Congolese (Republic of the Congo)', 'كونغولي', 'Congo', 43, CURRENT_TIMESTAMP),
    ('CRI', 'Costa Rican', 'كوستاريكي', 'Costa Rica', 44, CURRENT_TIMESTAMP),
    ('HRV', 'Croatian', 'كرواتي', 'Croatia', 45, CURRENT_TIMESTAMP),
    ('CUB', 'Cuban', 'كوبي', 'Cuba', 46, CURRENT_TIMESTAMP),
    ('CYP', 'Cypriot', 'قبرصي', 'Cyprus', 47, CURRENT_TIMESTAMP),
    ('CZE', 'Czech', 'تشيكي', 'Czechia', 48, CURRENT_TIMESTAMP),
    ('DNK', 'Danish', 'دنماركي', 'Denmark', 49, CURRENT_TIMESTAMP),
    ('DJI', 'Djiboutian', 'جيبوتي', 'Djibouti', 50, CURRENT_TIMESTAMP),
    ('DMA', 'Dominican (Dominica)', 'دومينيكي', 'Dominica', 51, CURRENT_TIMESTAMP),
    ('DOM', 'Dominican (Dominican Republic)', 'دومينيكاني', 'Dominican Republic', 52, CURRENT_TIMESTAMP),
    ('NLD', 'Dutch', 'هولندي', 'Netherlands', 53, CURRENT_TIMESTAMP),
    ('ECU', 'Ecuadorian', 'إكوادوري', 'Ecuador', 54, CURRENT_TIMESTAMP),
    ('EGY', 'Egyptian', 'مصري', 'Egypt', 55, CURRENT_TIMESTAMP),
    ('ARE', 'Emirati', 'إماراتي', 'United Arab Emirates', 56, CURRENT_TIMESTAMP),
    ('GNQ', 'Equatorial Guinean', 'غيني استوائي', 'Equatorial Guinea', 57, CURRENT_TIMESTAMP),
    ('ERI', 'Eritrean', 'إريتري', 'Eritrea', 58, CURRENT_TIMESTAMP),
    ('EST', 'Estonian', 'إستوني', 'Estonia', 59, CURRENT_TIMESTAMP),
    ('ETH', 'Ethiopian', 'إثيوبي', 'Ethiopia', 60, CURRENT_TIMESTAMP),
    ('FJI', 'Fijian', 'فيجي', 'Fiji', 61, CURRENT_TIMESTAMP),
    ('PHL', 'Filipino', 'فلبيني', 'Philippines', 62, CURRENT_TIMESTAMP),
    ('FIN', 'Finnish', 'فنلندي', 'Finland', 63, CURRENT_TIMESTAMP),
    ('FRA', 'French', 'فرنسي', 'France', 64, CURRENT_TIMESTAMP),
    ('GAB', 'Gabonese', 'غابوني', 'Gabon', 65, CURRENT_TIMESTAMP),
    ('GMB', 'Gambian', 'غامبي', 'Gambia', 66, CURRENT_TIMESTAMP),
    ('GEO', 'Georgian', 'جورجي', 'Georgia', 67, CURRENT_TIMESTAMP),
    ('DEU', 'German', 'ألماني', 'Germany', 68, CURRENT_TIMESTAMP),
    ('GHA', 'Ghanaian', 'غاني', 'Ghana', 69, CURRENT_TIMESTAMP),
    ('GRC', 'Greek', 'يوناني', 'Greece', 70, CURRENT_TIMESTAMP),
    ('GRD', 'Grenadian', 'غرينادي', 'Grenada', 71, CURRENT_TIMESTAMP),
    ('GTM', 'Guatemalan', 'غواتيمالي', 'Guatemala', 72, CURRENT_TIMESTAMP),
    ('GIN', 'Guinean', 'غيني', 'Guinea', 73, CURRENT_TIMESTAMP),
    ('GUY', 'Guyanese', 'غوياني', 'Guyana', 74, CURRENT_TIMESTAMP),
    ('HTI', 'Haitian', 'هايتي', 'Haiti', 75, CURRENT_TIMESTAMP),
    ('HND', 'Honduran', 'هندوراسي', 'Honduras', 76, CURRENT_TIMESTAMP),
    ('HKG', 'Hong Konger', 'هونغ كونغي', 'Hong Kong', 77, CURRENT_TIMESTAMP),
    ('HUN', 'Hungarian', 'مجري', 'Hungary', 78, CURRENT_TIMESTAMP),
    ('KIR', 'I-Kiribati', 'كيريباتي', 'Kiribati', 79, CURRENT_TIMESTAMP),
    ('ISL', 'Icelandic', 'آيسلندي', 'Iceland', 80, CURRENT_TIMESTAMP),
    ('IND', 'Indian', 'هندي', 'India', 81, CURRENT_TIMESTAMP),
    ('IDN', 'Indonesian', 'إندونيسي', 'Indonesia', 82, CURRENT_TIMESTAMP),
    ('IRN', 'Iranian', 'إيراني', 'Iran', 83, CURRENT_TIMESTAMP),
    ('IRQ', 'Iraqi', 'عراقي', 'Iraq', 84, CURRENT_TIMESTAMP),
    ('IRL', 'Irish', 'أيرلندي', 'Ireland', 85, CURRENT_TIMESTAMP),
    ('ISR', 'Israeli', 'إسرائيلي', 'Israel', 86, CURRENT_TIMESTAMP),
    ('ITA', 'Italian', 'إيطالي', 'Italy', 87, CURRENT_TIMESTAMP),
    ('CIV', 'Ivorian', 'إيفواري', 'Côte d''Ivoire', 88, CURRENT_TIMESTAMP),
    ('JAM', 'Jamaican', 'جامايكي', 'Jamaica', 89, CURRENT_TIMESTAMP),
    ('JPN', 'Japanese', 'ياباني', 'Japan', 90, CURRENT_TIMESTAMP),
    ('JOR', 'Jordanian', 'أردني', 'Jordan', 91, CURRENT_TIMESTAMP),
    ('KAZ', 'Kazakhstani', 'كازاخستاني', 'Kazakhstan', 92, CURRENT_TIMESTAMP),
    ('KEN', 'Kenyan', 'كيني', 'Kenya', 93, CURRENT_TIMESTAMP),
    ('KNA', 'Kittitian or Nevisian', 'سانت كيتسي', 'Saint Kitts and Nevis', 94, CURRENT_TIMESTAMP),
    ('XKX', 'Kosovar', 'كوسوفي', 'Kosovo', 95, CURRENT_TIMESTAMP),
    ('KWT', 'Kuwaiti', 'كويتي', 'Kuwait', 96, CURRENT_TIMESTAMP),
    ('KGZ', 'Kyrgyz', 'قيرغيزي', 'Kyrgyzstan', 97, CURRENT_TIMESTAMP),
    ('LAO', 'Lao', 'لاوسي', 'Laos', 98, CURRENT_TIMESTAMP),
    ('LVA', 'Latvian', 'لاتفي', 'Latvia', 99, CURRENT_TIMESTAMP),
    ('LBN', 'Lebanese', 'لبناني', 'Lebanon', 100, CURRENT_TIMESTAMP),
    ('LBR', 'Liberian', 'ليبيري', 'Liberia', 101, CURRENT_TIMESTAMP),
    ('LBY', 'Libyan', 'ليبي', 'Libya', 102, CURRENT_TIMESTAMP),
    ('LIE', 'Liechtensteiner', 'ليختنشتايني', 'Liechtenstein', 103, CURRENT_TIMESTAMP),
    ('LTU', 'Lithuanian', 'ليتواني', 'Lithuania', 104, CURRENT_TIMESTAMP),
    ('LUX', 'Luxembourgish', 'لوكسمبورغي', 'Luxembourg', 105, CURRENT_TIMESTAMP),
    ('MAC', 'Macanese', 'ماكاوي', 'Macau', 106, CURRENT_TIMESTAMP),
    ('MKD', 'Macedonian (North Macedonia)', 'مقدوني', 'North Macedonia', 107, CURRENT_TIMESTAMP),
    ('MDG', 'Malagasy', 'مدغشقري', 'Madagascar', 108, CURRENT_TIMESTAMP),
    ('MWI', 'Malawian', 'مالاوي', 'Malawi', 109, CURRENT_TIMESTAMP),
    ('MYS', 'Malaysian', 'ماليزي', 'Malaysia', 110, CURRENT_TIMESTAMP),
    ('MDV', 'Maldivian', 'مالديفي', 'Maldives', 111, CURRENT_TIMESTAMP),
    ('MLI', 'Malian', 'مالي', 'Mali', 112, CURRENT_TIMESTAMP),
    ('MLT', 'Maltese', 'مالطي', 'Malta', 113, CURRENT_TIMESTAMP),
    ('MHL', 'Marshallese', 'مارشالي', 'Marshall Islands', 114, CURRENT_TIMESTAMP),
    ('MRT', 'Mauritanian', 'موريتاني', 'Mauritania', 115, CURRENT_TIMESTAMP),
    ('MUS', 'Mauritian', 'موريشيوسي', 'Mauritius', 116, CURRENT_TIMESTAMP),
    ('MEX', 'Mexican', 'مكسيكي', 'Mexico', 117, CURRENT_TIMESTAMP),
    ('FSM', 'Micronesian', 'ميكرونيزي', 'Micronesia', 118, CURRENT_TIMESTAMP),
    ('MDA', 'Moldovan', 'مولدوفي', 'Moldova', 119, CURRENT_TIMESTAMP),
    ('MCO', 'Monegasque', 'موناكي', 'Monaco', 120, CURRENT_TIMESTAMP),
    ('MNG', 'Mongolian', 'منغولي', 'Mongolia', 121, CURRENT_TIMESTAMP),
    ('MNE', 'Montenegrin', 'جبل أسودي', 'Montenegro', 122, CURRENT_TIMESTAMP),
    ('MAR', 'Moroccan', 'مغربي', 'Morocco', 123, CURRENT_TIMESTAMP),
    ('LSO', 'Mosotho (Lesotho)', 'ليسوتي', 'Lesotho', 124, CURRENT_TIMESTAMP),
    ('BWA', 'Motswana (Botswanan)', 'بوتسواني', 'Botswana', 125, CURRENT_TIMESTAMP),
    ('MOZ', 'Mozambican', 'موزمبيقي', 'Mozambique', 126, CURRENT_TIMESTAMP),
    ('NAM', 'Namibian', 'ناميبي', 'Namibia', 127, CURRENT_TIMESTAMP),
    ('NRU', 'Nauruan', 'ناوروي', 'Nauru', 128, CURRENT_TIMESTAMP),
    ('NPL', 'Nepali', 'نيبالي', 'Nepal', 129, CURRENT_TIMESTAMP),
    ('NZL', 'New Zealander', 'نيوزيلندي', 'New Zealand', 130, CURRENT_TIMESTAMP),
    ('VUT', 'Ni-Vanuatu', 'فانواتي', 'Vanuatu', 131, CURRENT_TIMESTAMP),
    ('NIC', 'Nicaraguan', 'نيكاراغوي', 'Nicaragua', 132, CURRENT_TIMESTAMP),
    ('NGA', 'Nigerian', 'نيجيري', 'Nigeria', 133, CURRENT_TIMESTAMP),
    ('NER', 'Nigerien', 'نيجري', 'Niger', 134, CURRENT_TIMESTAMP),
    ('PRK', 'North Korean', 'كوري شمالي', 'Korea, Democratic People''s Republic of', 135, CURRENT_TIMESTAMP),
    ('NOR', 'Norwegian', 'نرويجي', 'Norway', 136, CURRENT_TIMESTAMP),
    ('OMN', 'Omani', 'عماني', 'Oman', 137, CURRENT_TIMESTAMP),
    ('PAK', 'Pakistani', 'باكستاني', 'Pakistan', 138, CURRENT_TIMESTAMP),
    ('PLW', 'Palauan', 'بالاوي', 'Palau', 139, CURRENT_TIMESTAMP),
    ('PSE', 'Palestinian', 'فلسطيني', 'Palestine', 140, CURRENT_TIMESTAMP),
    ('PAN', 'Panamanian', 'بنمي', 'Panama', 141, CURRENT_TIMESTAMP),
    ('PNG', 'Papua New Guinean', 'بابوي', 'Papua New Guinea', 142, CURRENT_TIMESTAMP),
    ('PRY', 'Paraguayan', 'باراغواياني', 'Paraguay', 143, CURRENT_TIMESTAMP),
    ('PER', 'Peruvian', 'بيروفي', 'Peru', 144, CURRENT_TIMESTAMP),
    ('POL', 'Polish', 'بولندي', 'Poland', 145, CURRENT_TIMESTAMP),
    ('PRT', 'Portuguese', 'برتغالي', 'Portugal', 146, CURRENT_TIMESTAMP),
    ('QAT', 'Qatari', 'قطري', 'Qatar', 147, CURRENT_TIMESTAMP),
    ('ROU', 'Romanian', 'روماني', 'Romania', 148, CURRENT_TIMESTAMP),
    ('RUS', 'Russian', 'روسي', 'Russian Federation', 149, CURRENT_TIMESTAMP),
    ('RWA', 'Rwandan', 'رواندي', 'Rwanda', 150, CURRENT_TIMESTAMP),
    ('LCA', 'Saint Lucian', 'سانت لوسي', 'Saint Lucia', 151, CURRENT_TIMESTAMP),
    ('SLV', 'Salvadoran', 'سلفادوري', 'El Salvador', 152, CURRENT_TIMESTAMP),
    ('SMR', 'Sammarinese', 'سان ماريني', 'San Marino', 153, CURRENT_TIMESTAMP),
    ('WSM', 'Samoan', 'ساموي', 'Samoa', 154, CURRENT_TIMESTAMP),
    ('STP', 'Sao Tomean', 'ساوتومي', 'Sao Tome and Principe', 155, CURRENT_TIMESTAMP),
    ('SAU', 'Saudi', 'سعودي', 'Saudi Arabia', 156, CURRENT_TIMESTAMP),
    ('SEN', 'Senegalese', 'سنغالي', 'Senegal', 157, CURRENT_TIMESTAMP),
    ('SRB', 'Serbian', 'صربي', 'Serbia', 158, CURRENT_TIMESTAMP),
    ('SYC', 'Seychellois', 'سيشلي', 'Seychelles', 159, CURRENT_TIMESTAMP),
    ('SLE', 'Sierra Leonean', 'سيراليوني', 'Sierra Leone', 160, CURRENT_TIMESTAMP),
    ('SGP', 'Singaporean', 'سنغافوري', 'Singapore', 161, CURRENT_TIMESTAMP),
    ('SVK', 'Slovak', 'سلوفاكي', 'Slovakia', 162, CURRENT_TIMESTAMP),
    ('SVN', 'Slovenian', 'سلوفيني', 'Slovenia', 163, CURRENT_TIMESTAMP),
    ('SLB', 'Solomon Islander', 'سليماني', 'Solomon Islands', 164, CURRENT_TIMESTAMP),
    ('SOM', 'Somali', 'صومالي', 'Somalia', 165, CURRENT_TIMESTAMP),
    ('ZAF', 'South African', 'جنوب أفريقي', 'South Africa', 166, CURRENT_TIMESTAMP),
    ('KOR', 'South Korean', 'كوري جنوبي', 'Korea, Republic of', 167, CURRENT_TIMESTAMP),
    ('SSD', 'South Sudanese', 'جنوب سوداني', 'South Sudan', 168, CURRENT_TIMESTAMP),
    ('ESP', 'Spanish', 'إسباني', 'Spain', 169, CURRENT_TIMESTAMP),
    ('LKA', 'Sri Lankan', 'سريلانكي', 'Sri Lanka', 170, CURRENT_TIMESTAMP),
    ('XXA', 'Stateless', 'عديم الجنسية', 'Stateless (ICAO XXA)', 171, CURRENT_TIMESTAMP),
    ('SDN', 'Sudanese', 'سوداني', 'Sudan', 172, CURRENT_TIMESTAMP),
    ('SUR', 'Surinamese', 'سورينامي', 'Suriname', 173, CURRENT_TIMESTAMP),
    ('SWZ', 'Swazi', 'إسواتيني', 'Eswatini', 174, CURRENT_TIMESTAMP),
    ('SWE', 'Swedish', 'سويدي', 'Sweden', 175, CURRENT_TIMESTAMP),
    ('CHE', 'Swiss', 'سويسري', 'Switzerland', 176, CURRENT_TIMESTAMP),
    ('SYR', 'Syrian', 'سوري', 'Syria', 177, CURRENT_TIMESTAMP),
    ('TWN', 'Taiwanese', 'تايواني', 'Taiwan', 178, CURRENT_TIMESTAMP),
    ('TJK', 'Tajik', 'طاجيكي', 'Tajikistan', 179, CURRENT_TIMESTAMP),
    ('TZA', 'Tanzanian', 'تنزاني', 'Tanzania', 180, CURRENT_TIMESTAMP),
    ('THA', 'Thai', 'تايلندي', 'Thailand', 181, CURRENT_TIMESTAMP),
    ('TLS', 'Timorese', 'تيموري', 'Timor-Leste', 182, CURRENT_TIMESTAMP),
    ('TGO', 'Togolese', 'توغولي', 'Togo', 183, CURRENT_TIMESTAMP),
    ('TON', 'Tongan', 'تونغي', 'Tonga', 184, CURRENT_TIMESTAMP),
    ('TTO', 'Trinidadian or Tobagonian', 'ترينيدادي', 'Trinidad and Tobago', 185, CURRENT_TIMESTAMP),
    ('TUN', 'Tunisian', 'تونسي', 'Tunisia', 186, CURRENT_TIMESTAMP),
    ('TUR', 'Turkish', 'تركي', 'Türkiye', 187, CURRENT_TIMESTAMP),
    ('TKM', 'Turkmen', 'تركماني', 'Turkmenistan', 188, CURRENT_TIMESTAMP),
    ('TUV', 'Tuvaluan', 'توفالي', 'Tuvalu', 189, CURRENT_TIMESTAMP),
    ('UGA', 'Ugandan', 'أوغندي', 'Uganda', 190, CURRENT_TIMESTAMP),
    ('UKR', 'Ukrainian', 'أوكراني', 'Ukraine', 191, CURRENT_TIMESTAMP),
    ('URY', 'Uruguayan', 'أوروغواياني', 'Uruguay', 192, CURRENT_TIMESTAMP),
    ('UZB', 'Uzbek', 'أوزبكي', 'Uzbekistan', 193, CURRENT_TIMESTAMP),
    ('VAT', 'Vatican', 'فاتيكاني', 'Holy See', 194, CURRENT_TIMESTAMP),
    ('VEN', 'Venezuelan', 'فنزويلي', 'Venezuela', 195, CURRENT_TIMESTAMP),
    ('VNM', 'Vietnamese', 'فيتنامي', 'Viet Nam', 196, CURRENT_TIMESTAMP),
    ('VCT', 'Vincentian', 'سانت فنسنتي', 'Saint Vincent and the Grenadines', 197, CURRENT_TIMESTAMP),
    ('YEM', 'Yemeni', 'يمني', 'Yemen', 198, CURRENT_TIMESTAMP),
    ('ZMB', 'Zambian', 'زامبي', 'Zambia', 199, CURRENT_TIMESTAMP),
    ('ZWE', 'Zimbabwean', 'زيمبابوي', 'Zimbabwe', 200, CURRENT_TIMESTAMP);

-- AlterTable
ALTER TABLE "employees" ADD COLUMN "nationality_code" VARCHAR(3);

-- CreateIndex
CREATE INDEX "employees_nationality_code_idx" ON "employees"("nationality_code");

-- AddForeignKey
ALTER TABLE "employees" ADD CONSTRAINT "employees_nationality_code_fkey" FOREIGN KEY ("nationality_code") REFERENCES "nationalities"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Normalise the free text already recorded: a value that is a listed nationality, country,
-- code or Arabic name (any case and spacing), or one of the unambiguous spellings below,
-- gets its code and the text is cleared. Anything else is left exactly as it was, with no
-- code, so HR can choose the right nationality — nothing is deleted or guessed.
WITH alias(spelling, code) AS (VALUES
    ('filipina', 'PHL'),
    ('philippine', 'PHL'),
    ('us', 'USA'),
    ('u.s.', 'USA'),
    ('u.s.a.', 'USA'),
    ('united states', 'USA'),
    ('uk', 'GBR'),
    ('u.k.', 'GBR'),
    ('great britain', 'GBR'),
    ('uae', 'ARE'),
    ('ksa', 'SAU'),
    ('saudi arabian', 'SAU'),
    ('turkey', 'TUR'),
    ('czech republic', 'CZE'),
    ('burma', 'MMR'),
    ('swaziland', 'SWZ'),
    ('ivory coast', 'CIV'),
    ('vietnam', 'VNM'),
    ('south korea', 'KOR'),
    ('north korea', 'PRK'),
    ('macedonian', 'MKD'),
    ('bruneian', 'BRN')
), matched AS (
    SELECT e.id, COALESCE(
        (SELECT n.code FROM "nationalities" n
          WHERE lower(btrim(e.nationality)) IN (lower(n.name), lower(n.country_name), lower(n.code)) OR btrim(e.nationality) = n.name_ar
          ORDER BY n.code LIMIT 1),
        (SELECT a.code FROM alias a WHERE a.spelling = lower(btrim(e.nationality)))
    ) AS code
    FROM "employees" e
    WHERE e.nationality IS NOT NULL AND btrim(e.nationality) <> ''
)
UPDATE "employees" e SET "nationality_code" = m.code, "nationality" = NULL
FROM matched m WHERE e.id = m.id AND m.code IS NOT NULL;
