// Hospital baseline organisation (spec §2.9): 5 departments, 47 nursing units, 582 beds.
// This is editable configuration, not a constant (rule W3) — seeded only when absent.
// Carried over from V03 app/src/data/seed.ts.

export const DEPARTMENTS = [
  { code: "EMAC", name: "Emergency & Acute Care", description: "Emergency departments, urgent care and clinical decision units" },
  { code: "SURG", name: "Surgical & Perioperative Services", description: "Operating rooms, recovery and day surgery" },
  { code: "CRIT", name: "Critical Care & Intensive Services", description: "ICU, NICU, PICU, CCU and high-dependency units" },
  { code: "GNSP", name: "General & Specialty Services", description: "Inpatient wards, outpatient clinics and specialty units" },
  { code: "CORP", name: "Administrative & Corporate Services", description: "Nursing admin, HR, infection control and support services" },
];

export const UNITS = [
  { code: "ER_MAIN", name: "ER Main / Adult", departmentCode: "EMAC", bedCount: 39, description: "Primary triage and emergency care for adults" },
  { code: "ER_MC", name: "ER M&C", departmentCode: "EMAC", bedCount: 32, description: "Emergency care for Mothers and Children" },
  { code: "UCC", name: "Urgent Care Center", departmentCode: "EMAC", bedCount: 15, description: "Urgent care for non-life-threatening needs" },
  { code: "CDU", name: "Clinical Decision Unit", departmentCode: "EMAC", bedCount: 32, description: "Observation unit for clinical decisions" },
  { code: "ER_COORD", name: "ER Coordinator", departmentCode: "EMAC", bedCount: 0, description: "Patient flow and resource management" },
  { code: "ED_NAV", name: "ED Navigation", departmentCode: "EMAC", bedCount: 8, description: "Patient routing and intake" },
  { code: "ED_ADMIN", name: "ED Admin", departmentCode: "EMAC", bedCount: 7, description: "Clerical support for Emergency Department" },
  { code: "OR", name: "Operating Room", departmentCode: "SURG", bedCount: 12, description: "Sterile surgical suites" },
  { code: "OR_COORD", name: "OR Coordinator", departmentCode: "SURG", bedCount: 0, description: "Surgical scheduling and theater flow" },
  { code: "PACU", name: "Recovery / PACU", departmentCode: "SURG", bedCount: 8, description: "Post-Anesthesia Care Unit" },
  { code: "DAY_SURG", name: "Day Surgery", departmentCode: "SURG", bedCount: 9, description: "Same-day surgical procedures" },
  { code: "PLASTER", name: "Plaster Unit", departmentCode: "SURG", bedCount: 9, description: "Orthopedic casting and splinting" },
  { code: "ICU_MAIN", name: "ICU Main", departmentCode: "CRIT", bedCount: 79, description: "Intensive care for critically ill adults" },
  { code: "ICU_EXT", name: "ICU Extension", departmentCode: "CRIT", bedCount: 28, description: "Overflow critical care capacity" },
  { code: "NICU", name: "Neonatal Intensive Care", departmentCode: "CRIT", bedCount: 15, description: "Neonatal intensive care" },
  { code: "PICU", name: "Pediatric Intensive Care", departmentCode: "CRIT", bedCount: 15, description: "Pediatric intensive care" },
  { code: "CCU", name: "Coronary Care Unit", departmentCode: "CRIT", bedCount: 10, description: "Cardiac intensive care" },
  { code: "BURN_ICU", name: "Burn ICU", departmentCode: "CRIT", bedCount: 6, description: "Specialized care for burn trauma" },
  { code: "ASU", name: "Acute Stabilization Unit", departmentCode: "CRIT", bedCount: 6, description: "Acute stabilization" },
  { code: "HDU", name: "High Dependency Unit", departmentCode: "CRIT", bedCount: 6, description: "Step-down unit" },
  { code: "INP_WARDS", name: "Inpatient Wards", departmentCode: "GNSP", bedCount: 98, description: "General and specialized acute care (3A–5B)" },
  { code: "AKU", name: "Allergy and Kidney Unit", departmentCode: "GNSP", bedCount: 14, description: "Allergy and kidney unit" },
  { code: "REHAB", name: "Rehabilitation", departmentCode: "GNSP", bedCount: 17, description: "Rehabilitation and physical therapy" },
  { code: "PEDIA", name: "Pediatric Inpatient", departmentCode: "GNSP", bedCount: 15, description: "Inpatient pediatric care" },
  { code: "LND", name: "Labor and Delivery", departmentCode: "GNSP", bedCount: 15, description: "Labor and delivery" },
  { code: "OBGYNE", name: "Obstetrics & Gynecology", departmentCode: "GNSP", bedCount: 17, description: "Obstetrics and gynecology" },
  { code: "NBS", name: "Newborn Screening", departmentCode: "GNSP", bedCount: 3, description: "Newborn screening unit" },
  { code: "OPD_DENTAL", name: "OPD / Dental", departmentCode: "GNSP", bedCount: 23, description: "Outpatient clinics" },
  { code: "JAIL", name: "Jail Ward", departmentCode: "GNSP", bedCount: 12, description: "Secured unit for incarcerated patients" },
  { code: "RRT", name: "Respiratory Rehab", departmentCode: "GNSP", bedCount: 5, description: "Respiratory rehabilitation therapy" },
  { code: "ECHO_EEG", name: "ECHO / EEG", departmentCode: "GNSP", bedCount: 2, description: "Diagnostic electrical testing" },
  { code: "ENDO", name: "Endoscopy", departmentCode: "GNSP", bedCount: 5, description: "GI visual diagnostics" },
  { code: "RADIOLOGY", name: "Radiology", departmentCode: "GNSP", bedCount: 6, description: "Imaging services (X-Ray/CT/MRI)" },
  { code: "BLOOD_BANK", name: "Blood Bank", departmentCode: "GNSP", bedCount: 2, description: "Blood storage and donation" },
  { code: "LAB", name: "Laboratory", departmentCode: "GNSP", bedCount: 0, description: "Clinical pathology diagnostics" },
  { code: "DIABETIC", name: "Diabetic Center", departmentCode: "GNSP", bedCount: 10, description: "Specialized diabetes management" },
  { code: "DISCHARGE", name: "Discharge Lounge", departmentCode: "GNSP", bedCount: 2, description: "Transition area for departing patients" },
  { code: "NURS_ADMIN", name: "Nursing Admin", departmentCode: "CORP", bedCount: 0, description: "Nursing staff management" },
  { code: "HR", name: "Human Resources", departmentCode: "CORP", bedCount: 0, description: "Human resources and payroll" },
  { code: "IC", name: "Infection Control", departmentCode: "CORP", bedCount: 0, description: "Infection control" },
  { code: "PAT_EXP", name: "Patient Experience", departmentCode: "CORP", bedCount: 0, description: "Patient satisfaction and feedback" },
  { code: "PAT_AFFAIRS", name: "Patient Affairs", departmentCode: "CORP", bedCount: 0, description: "Admissions and patient rights" },
  { code: "ACADEMIC", name: "Academic Affairs", departmentCode: "CORP", bedCount: 0, description: "Medical education and training" },
  { code: "BIZ_CENTER", name: "Business Center", departmentCode: "CORP", bedCount: 0, description: "Finance and billing" },
  { code: "IDARA", name: "Idara", departmentCode: "CORP", bedCount: 0, description: "General management office" },
  { code: "STORE", name: "Store", departmentCode: "CORP", bedCount: 0, description: "Supply chain and inventory" },
  { code: "HOME_CARE", name: "Home Care", departmentCode: "CORP", bedCount: 0, description: "Coordination of home-based medical care" },
];
