#!/bin/bash
# ops/vps/db-init.sh — first-time database and settings on the VPS (decision D-57).
# Run ONCE as root after setup-host.sh (README.md §3):
#
#   sudo SITE_HOST=nurse.<hospital-domain> ACME_EMAIL=it@<hospital-domain> \
#        DATA_RESIDENCY_REGION=<KSA site id> /opt/nurseapp/vps/db-init.sh
#
# 1. Creates the database nurseapp_v04 and the four roles (ops/db/01_roles.sql,
#    02_grants.sql), each with a new random password.
# 2. Writes the settings files, root-only (0600):
#      /etc/nurseapp/app.env      runtime DATABASE_URL + newly generated JWT_SECRET and the
#                                 four encryption keys
#      /etc/nurseapp/migrate.env  migration role URL — used only by the release step
#      /etc/nurseapp/deploy.env   host name, certificate e-mail
#    and the backup role's password for the backup kit (~postgres/.pgpass).
# Refuses to overwrite a settings file that exists (it would orphan encrypted data).
# Passwords and keys are generated here and never printed: copy /etc/nurseapp
# to the hospital's offline key store (README.md §3, step 3).

set -euo pipefail
[[ $EUID -eq 0 ]] || { echo "run as root (sudo)" >&2; exit 1; }
: "${SITE_HOST:?SITE_HOST is the public host name, e.g. nurse.hospital.sa}"
: "${ACME_EMAIL:?ACME_EMAIL receives certificate expiry notices}"
: "${DATA_RESIDENCY_REGION:?DATA_RESIDENCY_REGION names the KSA data-centre site (README.md §1)}"
OPS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF="${NURSEAPP_CONF:-/etc/nurseapp}"
DB="${DB_NAME:-nurseapp_v04}"
read -r -a PSQL <<< "${DB_SUPERUSER_PSQL:-sudo -u postgres psql}"
psql_su() { "${PSQL[@]}" -X -q -v ON_ERROR_STOP=1 "$@"; }

for f in app.env migrate.env deploy.env; do
  [[ -e "$CONF/$f" ]] && { echo "$CONF/$f exists — refusing to overwrite settings (and the keys in them)" >&2; exit 1; }
done
install -d -m 700 "$CONF"
umask 077

pw() { openssl rand -hex 24; }          # URL-safe: no encoding needed
key() { openssl rand -base64 32; }
RUNTIME_PW="$(pw)"; MIGRATION_PW="$(pw)"; BACKUP_PW="$(pw)"; AUDIT_PW="$(pw)"

echo "== database $DB and roles"
psql_su -d postgres <<SQL
SELECT 'CREATE DATABASE $DB' WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$DB')\\gexec
SQL
psql_su -d "$DB" < "$OPS/db/01_roles.sql"
# Passwords go in on stdin, with statement logging off for this session.
psql_su -d "$DB" <<SQL
SET log_statement = 'none';
ALTER ROLE nurseapp_runtime PASSWORD '$RUNTIME_PW';
ALTER ROLE nurseapp_migration PASSWORD '$MIGRATION_PW';
ALTER ROLE nurseapp_backup PASSWORD '$BACKUP_PW';
ALTER ROLE nurseapp_audit_reader PASSWORD '$AUDIT_PW';
SQL
psql_su -d "$DB" < "$OPS/db/02_grants.sql"

echo "== settings files in $CONF"
cat > "$CONF/app.env" <<ENV
# Generated by ops/vps/db-init.sh on $(date -u +%F). Root-only. Copy this folder to the offline key store.
DATABASE_URL=postgresql://nurseapp_runtime:$RUNTIME_PW@db.host:5432/$DB
JWT_SECRET=$(openssl rand -hex 32)
MFA_ENCRYPTION_KEY=$(key)
DOCUMENT_ENCRYPTION_KEY=$(key)
PDPL_FIELD_ENCRYPTION_KEY=$(key)
PDPL_BLIND_INDEX_PEPPER=$(key)
CORS_ORIGIN=https://$SITE_HOST
APP_BASE_URL=https://$SITE_HOST
DATA_RESIDENCY_REGION=$DATA_RESIDENCY_REGION
PDPL_ALLOWED_REGIONS=$DATA_RESIDENCY_REGION
BACKUP_RETENTION_DAYS=30
# E-mail (D-47): the hospital relay — empty keeps e-mail off.
SMTP_HOST=
SMTP_FROM=
BREAK_GLASS_ALERT_EMAILS=
# Telegram (D-66): mock until the bot token is set; messages carry no personal data.
NOTIFICATION_DRIVER=mock
TELEGRAM_BOT_TOKEN=
TELEGRAM_BOT_USERNAME=
BREAK_GLASS_ALERT_TELEGRAM_CHAT_IDS=
ENV
cat > "$CONF/migrate.env" <<ENV
MIGRATION_DATABASE_URL=postgresql://nurseapp_migration:$MIGRATION_PW@db.host:5432/$DB
DATABASE_URL=postgresql://nurseapp_migration:$MIGRATION_PW@db.host:5432/$DB
ENV
cat > "$CONF/deploy.env" <<ENV
SITE_HOST=$SITE_HOST
ACME_EMAIL=$ACME_EMAIL
DB_NAME=$DB
ENV
cat > "$CONF/audit-reader.env" <<ENV
# For compliance queries over an SSH tunnel (README.md §7): psql "postgresql://nurseapp_audit_reader:…@localhost:5432/$DB"
AUDIT_READER_PASSWORD=$AUDIT_PW
ENV

if [[ -z "${DB_SUPERUSER_PSQL:-}" ]]; then
  # The backup kit connects as nurseapp_backup over 127.0.0.1 (ops/backup README "Environment contract").
  PGPASS=/var/lib/postgresql/.pgpass
  grep -v ':nurseapp_backup:' "$PGPASS" 2>/dev/null > "$PGPASS.new" || true
  echo "127.0.0.1:5432:*:nurseapp_backup:$BACKUP_PW" >> "$PGPASS.new"
  mv "$PGPASS.new" "$PGPASS"; chown postgres:postgres "$PGPASS"; chmod 600 "$PGPASS"
fi

echo
echo "Done. Settings are in $CONF (root-only). Before anything else:"
echo "  1. copy $CONF to the hospital's offline key store (without the keys, encrypted data cannot be read);"
echo "  2. set the e-mail settings in $CONF/app.env when the relay is ready;"
echo "  3. set up backups (README.md §5), then the first release (README.md §6)."
