import type { GuideSection } from '../types';

export const ADMIN: GuideSection[] = [
  {
    id: 'administration',
    title: 'Nursing Administration',
    route: '/admin',
    summary: 'Accounts, roles, approvals, hospital set-up, data protection and system tools. HR Admins see the people and data tabs; System Admins also see the system tabs, and the people tabs only while elevated.',
    audience: 'HR Admin and System Admin',
    roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
    where: 'Side menu → Nursing Administration.',
    flows: ['role-grant', 'pam', 'baseline-import'],
    tables: [
      {
        title: 'The tabs',
        columns: ['Tab', 'Purpose', 'Who', 'Changes need', 'Audited'],
        rows: [
          ['Accounts', 'Logins: create, reset, deactivate, link to a staff record', 'HR Admin; System Admin (elevated)', '—', 'Yes'],
          ['Role assignments', 'Grant and revoke Supervisor / HR Admin / System Admin', 'HR Admin; System Admin (elevated)', 'Second admin for System Admin and hospital-wide HR Admin', 'Yes'],
          ['Approvals', 'Decide protected changes', 'HR Admin; System Admin (elevated)', 'A different administrator', 'Yes'],
          ['Hospital baseline import', 'Load departments, units, beds, positions, credential categories and types from a file', 'Hospital-wide HR Admin; System Admin (elevated)', 'Second hospital-wide admin', 'Yes'],
          ['Data protection', 'Personal-data requests; the processing register and its sign-off', 'HR Admin; System Admin (elevated)', 'Erasure: a System Admin', 'Yes (register changes: high priority)'],
          ['Eligibility logic', 'Shadow mode for a new version of the eligibility rules', 'Read: HR, System Admin; decide: hospital-wide HR Admin', '—', 'Yes'],
          ['Privileged access', 'Elevate System Admin rights for 1–4 hours', 'System Admin', 'A reason', 'Yes'],
          ['Background jobs', 'Schedules, last runs, run now; business health', 'System Admin', '—', 'Yes'],
          ['Telegram inbox', 'Messages the simulated Telegram gateway kept; test messages', 'System Admin', '—', '—'],
          ['SCFHS registry', 'The simulated SCFHS answers used until real SCFHS access', 'System Admin', '—', 'Yes'],
          ['Badge simulator', 'Simulated clock events for demonstrations; off on the live server (setting BADGE_SIMULATOR)', 'System Admin', '—', 'Yes'],
          ['API clients', 'Other systems allowed to call the API (FHIR reads, badge events)', 'System Admin', '—', 'Yes'],
          ['Access matrix', 'Who may do what, by area (read only)', 'Everyone in Administration', '—', '—'],
        ],
      },
    ],
    callouts: [
      { kind: 'warning', text: 'Nobody manages their own account, grants or revokes their own role, or decides their own request. The break-glass account is managed outside the application.' },
      { kind: 'info', text: 'Telegram inbox, SCFHS registry and Badge simulator are demonstration tools: they hold synthetic data only and stand in for systems the hospital has not connected yet. On the live server the SCFHS registry and the Telegram inbox are in use; the Badge simulator is switched off.' },
    ],
    tasks: [
      {
        id: 'new-account',
        title: 'Create a login account',
        status: 'IMPLEMENTED',
        purpose: 'Give someone a login without e-mail (or for a person with no staff record).',
        who: 'HR Admin; System Admin while elevated. An account without a staff link needs hospital-wide scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Accounts → New account.', 'E-mail (the sign-in name), display name, a first password (12–72 characters).', 'Employee id (optional) links the login to a staff record, which gives the self-service pages.', 'Create. Give the password to the person in person or by phone, never in the same message as the e-mail.'],
        result: 'The account exists with no extra role; audited.',
        approval: 'None.',
        next: 'Role assignments if the person needs a role. Supervisor and HR roles must set up two-factor sign-in at first sign-in.',
        related: ['roles', 'nurses'],
        keywords: ['create account', 'new user', 'add user', 'login'],
      },
      {
        id: 'account-actions',
        title: 'Reset, change e-mail, reset two-factor, deactivate',
        status: 'IMPLEMENTED',
        purpose: 'Help a user who is locked out or has changed details.',
        who: 'HR Admin; System Admin while elevated. Not on your own account, never on break-glass.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['Confirm who is asking before any of these.'],
        steps: [
          'Send reset link: a link to the account\'s own e-mail, valid 24 hours.',
          'Change e-mail: a confirmation link goes to the new address (valid 30 minutes); nothing changes until the person opens it; the old address is told.',
          'Reset two-factor: removes the authenticator and signs the account out; a new one is set up at next sign-in.',
          'Telegram link: shows a QR code the person scans to connect Telegram (15 minutes, single use).',
          'Deactivate / Activate: blocks or restores sign-in.',
        ],
        result: 'Each action is audited.',
        approval: 'None.',
        next: '—',
        problems: [{ problem: 'Deactivate refused', fix: 'It would leave no usable System Admin.' }],
        related: ['security'],
        keywords: ['reset password for user', 'locked out', 'lost phone', 'deactivate user', 'change email'],
      },
      {
        id: 'grant-role',
        title: 'Grant or revoke a role',
        status: 'IMPLEMENTED',
        purpose: 'Give or remove Supervisor, HR Admin or System Admin rights within a scope.',
        who: 'HR Admin or System Admin (elevated), covering the scope granted; never on their own account.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: [
          'Role assignments → Grant role.',
          'Account, role, scope type (Units, Departments, System-wide) and the units or departments.',
          'Reason — a real sentence of 20+ characters (it is kept in the audit trail).',
          'Expiry (optional): Supervisor at most 90 days, others at most 365.',
          'Submit. To revoke: Revoke on the row, reason of 10+ characters.',
        ],
        result: 'Supervisor, or HR Admin for units / departments: applied at once. System Admin, or HR Admin hospital-wide: "Submitted for approval — a second administrator must approve it".',
        approval: 'Four-eyes for System Admin and hospital-wide HR Admin.',
        next: 'Approvals (for the protected ones).',
        problems: [
          { problem: '"already holds an active assignment for this role and scope type"', fix: 'One active row per person, role and scope type. To change the units: Revoke the row, then Grant again.' },
          { problem: 'Cannot revoke the last System Admin', fix: 'Grant another System Admin first.' },
        ],
        related: ['approvals', 'roles'],
        flow: 'role-grant',
        keywords: ['grant role', 'make supervisor', 'give access', 'revoke role', 'remove access', 'how do i approve a request'],
      },
      {
        id: 'baseline',
        title: 'Import the hospital baseline',
        status: 'IMPLEMENTED',
        purpose: 'Load the hospital\'s set-up in one step from a baseline file.',
        who: 'Hospital-wide HR Admin or System Admin (elevated); approved by another hospital-wide administrator.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Hospital baseline import → Choose file (JSON) → Preview.', 'Rows: Create, Unchanged, Conflict, Rejected — with totals of beds and credential fields.', 'Conflicts and rejected rows are fixed on the normal screens, never by the import.', 'Write the reason (10+ characters) and Request import.'],
        result: 'A pending request. When approved, it is applied in one step or not at all.',
        approval: 'Four-eyes.',
        next: 'Approvals.',
        related: ['workforce', 'credentials', 'approvals'],
        flow: 'baseline-import',
        keywords: ['baseline', 'import', 'hospital setup', 'master data'],
      },
      {
        id: 'dsr-queue',
        title: 'Answer personal-data requests',
        status: 'IMPLEMENTED',
        purpose: 'Handle an employee\'s request to see, export, correct or erase their personal data (PDPL).',
        who: 'HR Admin or System Admin (elevated) within scope; not your own request. Erasure: a System Admin other than whoever logged it.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: [
          'Data protection → Personal data requests (open ones shown; filter by type).',
          'Log request: record one received on paper or by e-mail.',
          'Start review, then Approve: access / portability → the package is downloadable for 30 days; correction → correct the record, then Complete with what changed.',
          'Decline with a reason (10+ characters) when it cannot be granted.',
          'Erasure (System Admin): read the warning, type the employee\'s job number, Erase.',
        ],
        result: 'Each step is audited; the employee follows the status on My data. The answer is due within 30 days (shown as Due).',
        approval: 'Erasure needs a System Admin.',
        next: '—',
        related: ['self-service'],
        flow: 'pdpl-request',
        keywords: ['pdpl', 'personal data', 'data request', 'erasure', 'export data', 'privacy'],
      },
      {
        id: 'register',
        title: 'Maintain the processing register',
        status: 'IMPLEMENTED',
        purpose: 'Record the lawful basis, purpose and retention for each kind of sensitive data.',
        who: 'Edit: System Admin (elevated). Sign-off: HR Admin or System Admin acting for the Data Protection Officer.',
        roles: ['SYSTEM_ADMIN', 'HR_ADMIN'],
        steps: ['Data protection → Edit an entry: purpose, retention, active, reason (10+).', 'Sign-off: Record sign-off with title and note, confirm — once a year or after a change.'],
        result: 'Audited as high priority. A data kind without an active entry cannot be recorded at all.',
        approval: 'None.',
        next: '—',
        related: [],
        keywords: ['processing register', 'dpo', 'sign-off', 'lawful basis', 'retention'],
      },
      {
        id: 'shadow',
        title: 'Review a new version of the eligibility rules',
        status: 'IMPLEMENTED',
        purpose: 'Check that new eligibility logic judges nurses correctly before it takes over.',
        who: 'Hospital-wide HR Admin decides; HR and System Admin read.',
        roles: ['HR_ADMIN'],
        steps: ['Eligibility logic: the active and the shadow version.', 'For each nurse the new version would judge differently: New logic is right, or Reject, with a note (10+).', 'Promote when allowed (7 days without disagreement, or every finding approved) — or Retire.'],
        result: 'The shadow version never changes a result. Promotion recalculates every nurse at once; audited.',
        approval: 'None beyond the HR decision.',
        next: 'Eligibility.',
        related: ['eligibility'],
        keywords: ['shadow mode', 'eligibility logic', 'new rules', 'promote'],
      },
      {
        id: 'elevate',
        title: 'Elevate System Admin rights',
        status: 'IMPLEMENTED',
        purpose: 'Switch on dormant System Admin rights for a documented task.',
        who: 'System Admin.',
        roles: ['SYSTEM_ADMIN'],
        steps: ['Privileged access: reason (10+ characters) and hours (1–4).', 'Elevate. An orange "Elevated until …" tag appears at the top.', 'End elevation when finished.'],
        result: 'Admin tabs and Audit & Compliance work until the time ends. Audited with the reason.',
        approval: 'None.',
        next: 'The task you elevated for.',
        related: ['security', 'audit'],
        flow: 'pam',
        keywords: ['elevate', 'privileged access', 'pam', 'dormant', 'system admin'],
      },
      {
        id: 'jobs',
        title: 'Check background jobs and business health',
        status: 'IMPLEMENTED',
        purpose: 'See that the scheduled work runs (expiry scan, daily transitions, SCFHS sync, attendance alerts …).',
        who: 'System Admin.',
        roles: ['SYSTEM_ADMIN'],
        steps: ['Background jobs: business health (eligibility drift, e-mail and Telegram delivery) and each job\'s schedule and last runs.', 'Run now to repeat a job (it is safe: each run is keyed to its period).'],
        result: 'A run is recorded with its result.',
        approval: 'None.',
        next: '—',
        related: ['troubleshooting'],
        keywords: ['jobs', 'scheduler', 'health', 'drift', 'run now'],
      },
      {
        id: 'api-clients',
        title: 'Register an API client',
        status: 'IMPLEMENTED',
        purpose: 'Let another system (HIS, payroll, the badge system) call the API without a person.',
        who: 'System Admin.',
        roles: ['SYSTEM_ADMIN'],
        steps: ['API clients → add: name and scopes.', 'Copy the secret shown once into the other system.', 'Replace secret or Revoke when needed.'],
        result: 'The system exchanges its id and secret for a 15-minute token.',
        approval: 'None.',
        next: '—',
        related: ['attendance'],
        keywords: ['api client', 'fhir', 'integration', 'badge system', 'secret'],
      },
    ],
    keywords: ['administration', 'admin', 'settings'],
  },
  {
    id: 'audit',
    title: 'Audit & Compliance',
    route: '/audit',
    summary: 'The tamper-evident record of every change (who, what, when, before → after) and the log of every API request. It is written by the database, never by hand, and only System Admins read it.',
    audience: 'System Admin (elevated)',
    roles: ['SYSTEM_ADMIN'],
    where: 'Side menu → Audit & Compliance. Elevate first.',
    tasks: [
      {
        id: 'search-audit',
        title: 'Search the audit trail and verify the chain',
        status: 'IMPLEMENTED',
        purpose: 'Answer "who changed this, and when?" and prove nothing was altered.',
        who: 'System Admin while elevated.',
        roles: ['SYSTEM_ADMIN'],
        steps: ['Audit trail: filter by action (e.g. CREDENTIAL_VERIFIED), resource, resource id, priority, dates.', 'Expand a row for the details of the change.', 'Verify audit chain: confirms every entry still links to the one before.'],
        result: 'Read only. A broken chain lists the entries concerned.',
        approval: 'None.',
        next: '—',
        related: ['administration'],
        keywords: ['audit', 'who changed', 'history', 'verify chain', 'tamper'],
      },
      {
        id: 'request-log',
        title: 'Search the request log',
        status: 'IMPLEMENTED',
        purpose: 'See every API call — including refused and failed ones — for investigations and support.',
        who: 'System Admin while elevated.',
        roles: ['SYSTEM_ADMIN'],
        steps: ['Request log: filter by user id, path, method, outcome (2xx, 4xx, 401, 403, 5xx), error code, request id, dates.', 'Expand a row for the browser and session.'],
        result: 'Read only; kept 365 days. Request contents and search terms are never stored.',
        approval: 'None.',
        next: '—',
        related: ['troubleshooting'],
        keywords: ['request log', 'error', 'investigate', 'request id'],
      },
    ],
    keywords: ['audit', 'compliance', 'governance'],
  },
];
