import type { GuideSection } from '../types';

export const CREDENTIALS: GuideSection[] = [
  {
    id: 'credentials',
    title: 'Credentials',
    route: '/credentials',
    summary: 'Licences, certificates and documents (SCFHS licence, BLS, ACLS, Iqama …) with their evidence. HR verifies them; the dates decide whether they count. The tabs also hold the review queue, the requirements per unit, and the hospital catalogue of credential types.',
    audience: 'HR Admin and System Admin (decisions, within scope); Supervisor (compliance view: no identity numbers, no documents)',
    roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
    where: 'Side menu → Credentials. Tabs: Records, Review queue (HR), Requirements, Catalog, Categories. Nurses use My Credentials.',
    flows: ['credential-new', 'credential-renewal'],
    tables: [
      {
        title: 'Credential status (stored — decides eligibility)',
        columns: ['Status', 'Counts for eligibility?', 'Meaning'],
        rows: [
          ['Pending verification', 'No', 'Recorded, waiting for HR to verify'],
          ['Valid', 'Yes', 'Verified; more than 60 days before expiry'],
          ['Expiring soon', 'Yes', 'Verified; within 60 days of expiry'],
          ['Expired', 'No (grace may apply)', 'The day after the expiry date'],
          ['Suspended', 'No', 'Stopped by HR or by an SCFHS answer'],
          ['Revoked', 'No — final', 'Cancelled for good'],
        ],
      },
      {
        title: 'Lifecycle label (display only — never authorises anything)',
        columns: ['Label', 'Shown when'],
        rows: [
          ['Active', 'Current and not near expiry'],
          ['Subject to renew', 'Within 60 days of expiry'],
          ['Renewal under review', 'A renewal is waiting for HR'],
          ['Expired', 'Past its expiry'],
        ],
      },
      {
        title: 'Evidence (documents)',
        columns: ['Rule', 'Detail'],
        rows: [
          ['Files', 'PDF, JPEG, PNG or WebP, at most 10 MB; the content is checked, not just the name'],
          ['Virus scan', 'Every file is scanned on upload; a file that fails is refused'],
          ['Versions', 'Each upload is a new version; nothing is overwritten'],
          ['Review status', 'Pending review → Approved (when HR verifies or approves a renewal) or Rejected'],
          ['Who opens them', 'The holder and HR in scope. Supervisors never. Each view or download uses a single-use link valid 60 seconds'],
        ],
      },
    ],
    callouts: [
      { kind: 'warning', text: 'Nobody verifies, approves, rejects, suspends or revokes their own credential.' },
      { kind: 'info', text: 'Recording a credential for a nurse is done by the nurse on My Credentials. HR recording it on the nurse\'s behalf exists in the API but not yet on this screen.' },
    ],
    tasks: [
      {
        id: 'credential-records',
        title: 'A. Find and read credential records',
        status: 'IMPLEMENTED',
        purpose: 'See each nurse\'s credentials, their status and dates.',
        who: 'HR Admin, System Admin, Supervisor — nurses in scope (supervisors: compliance view).',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
        steps: [
          'Open Credentials → Records. The list is sorted by expiry date (soonest first).',
          'Read the Status tag, the lifecycle label, a gold "Grace until …" tag if grace is running, issue and expiry dates (with the Hijri expiry where recorded).',
          'HR only: search by an identifier number (licence, Iqama …) with at least 3 characters. The search is recorded; the number itself is never stored or logged.',
        ],
        result: 'Nothing changes.',
        approval: 'None.',
        next: 'Review queue for work waiting; Eligibility for the effect.',
        problems: [{ problem: 'No Evidence / SCFHS / Verify buttons', fix: 'You are a supervisor (compliance view), or the record is outside your HR scope.' }],
        related: ['eligibility', 'self-service'],
        keywords: ['credential status', 'licence', 'license', 'certificate', 'expiry', 'identify credential', 'search iqama'],
      },
      {
        id: 'review-queue',
        title: 'Work the review queue',
        status: 'IMPLEMENTED',
        purpose: 'See everything that waits for an HR decision.',
        who: 'HR Admin and System Admin within scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Open Credentials → Review queue.', 'It lists credentials Pending verification, renewals waiting, and documents pending review.', 'Work each row with Evidence, then Verify or Approve / Reject renewal.'],
        result: 'Each decision re-evaluates the nurse\'s eligibility at once.',
        approval: 'None (your decision is the review).',
        next: 'Eligibility shows the new result.',
        related: ['eligibility'],
        keywords: ['pending verification', 'queue', 'to do', 'waiting for hr'],
      },
      {
        id: 'evidence',
        title: 'B. Open, review and upload evidence',
        status: 'IMPLEMENTED',
        purpose: 'Check the document behind a credential, or add a newer one.',
        who: 'HR Admin / System Admin in scope, and the holder. Never supervisors.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'EMPLOYEE'],
        steps: ['Click Evidence on the credential row.', 'The versions are listed newest first with review status and scan status; "Current evidence" marks the approved one.', 'View or Download a CLEAN version (the link works once, for 60 seconds).', 'To add a version: Upload evidence and choose the file.'],
        result: 'An upload becomes a new version, Pending review. It is approved when HR verifies the credential or approves the renewal, and rejected otherwise.',
        approval: 'HR review through Verify or the renewal decision.',
        next: 'Verify (new credential) or Approve renewal.',
        problems: [
          { problem: 'Upload refused', fix: 'PDF, JPEG, PNG or WebP, at most 10 MB; the file must pass the virus scan. A revoked credential takes no evidence.' },
          { problem: 'No View / Download button', fix: 'Only CLEAN files can be opened, and only by the holder and HR.' },
        ],
        related: ['self-service'],
        keywords: ['evidence', 'document', 'upload', 'download', 'attachment', 'scan', 'proof'],
      },
      {
        id: 'verify',
        title: 'C. Verify a credential',
        status: 'IMPLEMENTED',
        purpose: 'Confirm that a recorded credential is genuine so that it counts.',
        who: 'HR Admin or System Admin in scope; never your own.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['The expiry date must be recorded if the type expires.', 'If the type requires evidence, a CLEAN document must be uploaded.'],
        steps: ['Open the credential\'s Evidence and compare the document with the recorded details.', 'For SCFHS-checked types, look at the SCFHS checks too.', 'Click Verify.'],
        result: 'Status becomes Valid, Expiring soon or Expired — from the expiry date, not chosen by hand. The newest clean pending document becomes the current evidence. Eligibility is re-evaluated at once.',
        approval: 'None — the verification is the approval.',
        next: 'Eligibility should now show the credential as met.',
        problems: [
          { problem: '"requires evidence: upload a document first"', fix: 'Upload the document under Evidence, then Verify.' },
          { problem: '"record its expiry date before verifying"', fix: 'The holder records the expiry; HR cannot verify without it.' },
          { problem: '"You cannot review or decide on your own credential"', fix: 'Ask another HR administrator.' },
        ],
        related: ['eligibility'],
        flow: 'credential-new',
        keywords: ['verify', 'verification', 'pending verification', 'approve credential'],
      },
      {
        id: 'scfhs',
        title: 'D. Check a licence with SCFHS',
        status: 'IMPLEMENTED',
        statusNote: 'Answers come from a simulated registry until the hospital has access to the SCFHS verification service; the screen says so.',
        purpose: 'Compare the recorded licence with what the Saudi Commission for Health Specialties reports.',
        who: 'HR Admin or System Admin in scope, for credential types set to "Check with SCFHS".',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['On the credential row click SCFHS (shown only for SCFHS-checked types).', 'Click Check with SCFHS now.', 'Read the answer and the history: when, trigger (on submission, nightly, on demand), SCFHS answer, details, action taken.'],
        result: 'Matches: nothing to do. Differs or not found: HR is notified. Suspended / revoked by SCFHS: HR is notified, and if the type is set to "Suspend on adverse SCFHS status" the credential is suspended at once. Unreachable: logged — try later. SCFHS never overwrites the record.',
        approval: 'None.',
        next: 'If it differs, check the evidence and correct the record (or suspend it). Revoking is always an HR decision.',
        problems: [{ problem: 'No SCFHS button', fix: 'The credential type is not set to "Check with SCFHS" (Catalog).' }],
        related: ['eligibility', 'administration'],
        flow: 'scfhs-check',
        keywords: ['scfhs', 'saudi council', 'licence check', 'license check', 'mismatch', 'discrepancy'],
      },
      {
        id: 'renewal',
        title: 'E. Renew a credential',
        status: 'IMPLEMENTED',
        purpose: 'Replace a credential\'s details and document with the renewed ones, before or after expiry.',
        who: 'The holder submits (My Credentials). HR Admin / System Admin in scope approves or rejects — never their own.',
        roles: ['EMPLOYEE', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['The renewed details, including the new expiry date.', 'The new document (PDF or image).'],
        steps: [
          'Holder: My Credentials → Renew on the credential (offered when it is Valid, Expiring soon or Expired and no renewal is waiting).',
          'Holder: enter the renewed details and Submit.',
          'Holder: click Evidence and upload the new document.',
          'The credential shows "Renewal under review"; the current one stays usable until its own expiry.',
          'HR: Credentials → Review queue → Evidence to check the new document.',
          'HR: Approve renewal — or Reject renewal with a reason.',
        ],
        result: 'Approve: the new details and document take effect, the status follows the new expiry date, any grace period closes. Reject: the staged details and the pending document are cleared; the approved credential is unchanged and any grace ends at once. Eligibility is re-evaluated either way.',
        approval: 'HR approval of the renewal (no second administrator).',
        next: 'Eligibility re-evaluates; the holder sees the result on My Credentials.',
        problems: [
          { problem: 'No Renew button', fix: 'The credential is Pending verification, Suspended or Revoked, or a renewal is already waiting.' },
          { problem: '"A renewal must state the new expiry date"', fix: 'Enter the new expiry date in the details.' },
          { problem: 'Approve refused: evidence required', fix: 'The holder (or HR) uploads the new document first.' },
        ],
        related: ['eligibility', 'notifications', 'scheduling', 'self-service'],
        flow: 'credential-renewal',
        keywords: ['renew', 'renewal', 'renew license', 'renew licence', 'expired credential', 'expiring', 'grace'],
      },
      {
        id: 'suspend',
        title: 'F. Suspend a credential',
        status: 'PARTIAL',
        statusNote: 'Suspending works. Lifting a suspension is not available in V04: the nurse records a new credential, which HR verifies.',
        purpose: 'Stop a credential from counting at once (for example during an investigation).',
        who: 'HR Admin or System Admin in scope; never their own. SCFHS can also suspend automatically for types set that way.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['On the credential row click Suspend.', 'Write the reason and submit.'],
        result: 'Status Suspended, audited as high priority; any grace ends. The nurse is INELIGIBLE wherever the credential is required, and future published shifts that are no longer valid return to Draft with the supervisors notified.',
        approval: 'None.',
        next: 'Tell the supervisor; record a new credential when the matter is resolved.',
        related: ['eligibility', 'scheduling'],
        flow: 'credential-suspend',
        keywords: ['suspend', 'suspension', 'block credential'],
      },
      {
        id: 'revoke',
        title: 'G. Revoke a credential',
        status: 'IMPLEMENTED',
        purpose: 'Cancel a credential for good (for example a false document).',
        who: 'HR Admin or System Admin in scope; never their own. Never automatic.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['On the credential row click Revoke.', 'Write the reason and submit.'],
        result: 'Status Revoked — final: it can never change, take evidence or be renewed. Same eligibility and roster effects as a suspension.',
        approval: 'None.',
        next: 'A valid credential must be recorded as a new one.',
        related: ['eligibility', 'scheduling'],
        flow: 'credential-suspend',
        keywords: ['revoke', 'cancel credential', 'false document'],
      },
      {
        id: 'requirements',
        title: 'H. Configure credential requirements',
        status: 'IMPLEMENTED',
        purpose: 'Say which credentials a unit (or a position in it) requires: Unit + optional Position + Credential type + Policy = Requirement.',
        who: 'HR Admin or System Admin with the unit in scope. Supervisors read the requirements of their units.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['The hospital\'s decision on what the unit requires. The system does not define clinical policy.'],
        steps: [
          'Credentials → Requirements → Add requirement.',
          'Unit: the unit it applies to.',
          'Position: one position, or leave blank for every position in the unit. A position-specific rule overrides the unit-wide one for the same type.',
          'Credential: the type required.',
          'Policy: MANDATORY (missing → ineligible), TRANSITION (warning until the deadline, then blocks — enter the deadline), or OPTIONAL (never affects eligibility).',
          'Click Create.',
        ],
        result: 'Applies at once: every affected nurse is re-evaluated in the same step; the message says how many. A new TRANSITION requirement notifies the nurses affected.',
        approval: 'None.',
        next: 'Check Eligibility for the unit; nurses see what they are missing on My Credentials.',
        problems: [{ problem: 'Need to change a requirement', fix: 'On screen: Delete it and add it again. (Editing in place exists in the API only.)' }],
        related: ['eligibility', 'workforce'],
        flow: 'requirement',
        keywords: ['requirement', 'mandatory', 'transition', 'what does transition mean', 'optional', 'deadline', 'unit requires', 'configure requirement'],
      },
      {
        id: 'categories',
        title: 'I. Manage credential categories',
        status: 'IMPLEMENTED',
        purpose: 'Group credential types (licence, life support, training …).',
        who: 'Hospital-wide HR Admin or System Admin; approved by another hospital-wide administrator.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Credentials → Categories → Add category (or Edit).', 'Code (capitals, e.g. LIFE_SUPPORT), name, description, display order (lower comes first).', 'Reason — at least 10 characters.', 'Submit.'],
        result: '"Submitted for approval — a second administrator must approve it (request #…)". Nothing changes until it is approved.',
        approval: 'Four-eyes: a different hospital-wide administrator in Approvals.',
        next: 'Approvals.',
        related: ['approvals'],
        flow: 'catalog-change',
        keywords: ['category', 'categories', 'display order'],
      },
      {
        id: 'catalog',
        title: 'J. Manage the credential catalogue (types)',
        status: 'IMPLEMENTED',
        purpose: 'Define a credential type: what is recorded, whether it expires, its grace period and SCFHS checking.',
        who: 'Hospital-wide HR Admin or System Admin; approved by another hospital-wide administrator.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: [
          'Credentials → Catalog → Add credential type (or Edit).',
          'Code, name, category, description.',
          'Has an expiry date; Evidence upload required; Grace days (0–90); display order; Active.',
          'Check with SCFHS (needs a field with the SCFHS registration data category) and, optionally, Suspend on adverse SCFHS status.',
          'Fields: key, label, type, required; mark one date field as the Issue date and one as the Expiry date; mark identity numbers as sensitive (encrypted). Order them with ↑ ↓.',
          'Reason — at least 10 characters. Submit.',
        ],
        result: 'A request with the change shown before → after. Field changes affect new entries only; recorded values are kept.',
        approval: 'Four-eyes: a different hospital-wide administrator approves in Approvals; refused if the type changed after the request.',
        next: 'Approvals; then Requirements can use the type.',
        problems: [{ problem: 'Grace days', fix: 'Grace days are hospital policy (0 until set). Grace applies only when a renewal is in progress.' }],
        related: ['approvals', 'eligibility'],
        flow: 'catalog-change',
        keywords: ['catalog', 'catalogue', 'credential type', 'template', 'fields', 'grace days', 'scfhs enabled'],
      },
      {
        id: 'hr-record',
        title: 'HR records a credential for a nurse',
        status: 'PARTIAL',
        statusNote: 'Available in the API (POST /credentials) but not on the Credentials screen yet.',
        purpose: 'Enter a credential on the nurse\'s behalf.',
        who: 'HR Admin or System Admin in scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['On screen today: ask the nurse to add it under My Credentials (or sign in with the nurse present).'],
        result: 'The credential starts as Pending verification.',
        approval: 'HR verifies it.',
        next: 'Verify.',
        related: ['self-service'],
        keywords: ['add credential for nurse', 'hr add credential', 'record credential'],
      },
    ],
    keywords: ['credential', 'licence', 'license', 'certificate', 'bls', 'acls', 'iqama'],
  },
  {
    id: 'eligibility',
    title: 'Eligibility',
    route: '/eligibility',
    summary: 'The workforce and clinical gate: for every nurse, whether they may work today and every reason why or why not. It is recalculated whenever a fact changes and every day; the roster checks it again for each shift date.',
    audience: 'HR Admin, System Admin, Supervisor (within scope); each nurse sees their own on My Credentials',
    roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
    where: 'Side menu → Eligibility. Filter by outcome at the top; waivers are listed below.',
    flows: ['eligibility-engine', 'ineligibility-resolution', 'waiver'],
    tables: [
      {
        title: 'Outcomes',
        columns: ['Outcome', 'Meaning', 'Scheduling', 'What to do'],
        rows: [
          ['ELIGIBLE', 'Nothing blocks', 'Can be rostered', 'Nothing'],
          ['ELIGIBLE WITH GRACE', 'An expired credential is accepted in its grace window because a renewal is in progress', 'Can be rostered; reliance is recorded', 'HR decides the renewal before grace ends'],
          ['ELIGIBLE WITH POLICY WARNING', 'A TRANSITION requirement is unmet before its deadline', 'Can be rostered until the deadline', 'Obtain the credential before the deadline'],
          ['INELIGIBLE', 'At least one blocking reason', 'Cannot be published; stays Draft', 'Fix each red reason'],
        ],
      },
      {
        title: 'Reasons and how to fix them',
        columns: ['Reason code', 'Means', 'Fix it in'],
        rows: [
          ['EMPLOYEE_NOT_FOUND / EMPLOYEE_DELETED', 'The record does not exist or was deleted', 'Nurses'],
          ['EMPLOYEE_NOT_ACTIVE', 'The employee status is not Active', 'No screen changes the status in V04: tell the system administrator'],
          ['POSITION_NOT_SCHEDULABLE', 'The position cannot be rostered (e.g. DON, DEPUTY_DON, ADMIN)', 'Nurses → Change position, or Workforce → Positions'],
          ['NO_CONTRACT_COVERAGE', 'No Approved or Active contract covers the date', 'Contracts: approve, renew or reinstate'],
          ['UNIT_NOT_ASSIGNED', 'The nurse has no unit, so no rules can be applied', 'Nurses → Edit → Unit'],
          ['CREDENTIAL_MISSING', 'A required credential is not on record', 'My Credentials (nurse adds it), then Verify'],
          ['CREDENTIAL_NOT_VERIFIED', 'Recorded but not verified', 'Credentials → Verify'],
          ['CREDENTIAL_EXPIRED', 'Past its expiry (the expiry date is the last valid day)', 'Renewal'],
          ['CREDENTIAL_NOT_YET_ISSUED', 'Issued after the date checked', 'Check the dates'],
          ['CREDENTIAL_EXPIRY_UNKNOWN', 'An expiring type without an expiry date', 'Correct the record (renewal with the date)'],
          ['CREDENTIAL_SUSPENDED / CREDENTIAL_REVOKED', 'Stopped by HR or SCFHS', 'Credentials (a new credential if needed)'],
          ['POLICY_TRANSITION_WARNING (amber)', 'Transition requirement unmet; blocks after the deadline', 'Obtain the credential'],
          ['GRACE_ACTIVE (amber)', 'Relying on a grace period', 'Decide the renewal'],
          ['WAIVER_ACTIVE (grey)', 'An emergency waiver covers a credential', 'Fix before it expires'],
          ['NO_REQUIREMENTS_CONFIGURED (grey)', 'The unit/position has no requirements: nothing was checked', 'Requirements (HR policy)'],
        ],
      },
    ],
    callouts: [
      { kind: 'info', text: 'Red reasons block, amber ones warn, grey ones are notes. Hover a reason to read its full message.' },
      { kind: 'warning', text: 'A unit with no requirements configured shows ELIGIBLE with a note: nothing was checked. That is a policy gap for HR to close, not a clean result.' },
    ],
    tasks: [
      {
        id: 'read-eligibility',
        title: 'Read a nurse\'s eligibility',
        status: 'IMPLEMENTED',
        purpose: 'Know who may work and why not.',
        who: 'HR Admin, System Admin, Supervisor (scope).',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
        steps: ['Open Eligibility.', 'Filter: All, Ineligible, Eligible (grace), Eligible (policy warning), Eligible.', 'Read the reasons and "Calculated" — when and by which event.'],
        result: 'Nothing changes. The stored result is for today; the roster checks each shift date separately.',
        approval: 'None.',
        next: 'Resolve ineligibility (next task) or go to Scheduling.',
        related: ['scheduling'],
        flow: 'eligibility-engine',
        keywords: ['eligible', 'ineligible', 'outcome', 'status', 'eligible_with_grace', 'what is eligible_with_grace', 'eligible with grace', 'grace', 'eligible_with_policy_warning', 'policy warning'],
      },
      {
        id: 'resolve-ineligible',
        title: 'Resolve an ineligible nurse',
        status: 'IMPLEMENTED',
        purpose: 'Get a blocked nurse back to work by fixing the cause, not the symptom.',
        who: 'HR Admin / System Admin fix records; supervisors read and ask HR.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
        steps: [
          'Open Eligibility and filter Ineligible.',
          'Select the nurse and read each red reason.',
          'Identify the root cause with the table above (contract, credential, unit or position).',
          'Correct the source record on its own page — Contracts, Credentials, Nurses.',
          'Eligibility recalculates automatically in the same step as your correction.',
          'Check the new result on Eligibility.',
          'Return to Scheduling.',
        ],
        result: 'The stored eligibility changes with an audit entry; the next roster check uses it.',
        approval: 'Whatever the correction needs (e.g. a contract approval by another HR person).',
        next: 'Scheduling.',
        related: ['contracts', 'credentials', 'nurses', 'scheduling'],
        flow: 'ineligibility-resolution',
        keywords: ['fix ineligible', 'resolve', 'blocked nurse', 'root cause', 'why is a nurse ineligible'],
      },
      {
        id: 'waiver',
        title: 'Grant an emergency waiver',
        status: 'IMPLEMENTED',
        purpose: 'In an emergency, let one blocking credential not count for a short time.',
        who: 'Supervisor or HR Admin only (not System Admin, not break-glass); never for your own credential.',
        roles: ['SUPERVISOR', 'HR_ADMIN'],
        before: ['A clinical justification.', 'The waiver covers one credential type, for at most 72 hours.'],
        steps: ['On Eligibility, click Grant waiver on the nurse (shown only when a credential blocks).', 'Choose the blocking credential.', 'Write the clinical justification and the expiry (≤ 72 hours).', 'Submit.'],
        result: 'Audited as high priority. That credential stops blocking until the waiver expires; the message shows the nurse\'s new eligibility. Shifts published in reliance on it are recorded.',
        approval: 'None.',
        next: 'Fix the credential before the waiver ends; the waivers list shows active and expired ones.',
        problems: [{ problem: 'No Grant waiver button', fix: 'Your role cannot waive, the block is not a credential (e.g. no contract), or it is your own record.' }],
        related: ['scheduling', 'credentials'],
        flow: 'waiver',
        keywords: ['waiver', 'emergency', 'exception', '72 hours', 'override'],
      },
    ],
    keywords: ['eligibility', 'clinical gate', 'allowed to work'],
  },
];
