import type { GuideSection } from '../types';

export const OPERATIONS: GuideSection[] = [
  {
    id: 'workforce',
    title: 'Workforce',
    route: '/workforce',
    summary: 'The hospital\'s structure: departments, units and their beds, positions, and how many staff each unit needs per shift. Everyone can read it; HR keeps it current. Eligibility, the roster and the KPIs all read from here.',
    audience: 'Everyone reads; HR Admin and System Admin change it (hospital-wide for structure, unit scope for beds and coverage)',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    where: 'Side menu → Workforce. Tabs: Units, Departments, Positions, Coverage targets.',
    flows: ['hospital-workflow'],
    tables: [
      {
        title: 'How workforce data feeds the rest',
        columns: ['Item', 'Used by'],
        rows: [
          ['Units (and the nurse\'s unit)', 'Requirements, eligibility, scopes, the roster (a nurse works only in the home unit)'],
          ['Positions (schedulable or not)', 'Eligibility (non-schedulable positions cannot be rostered), requirements per position'],
          ['Beds', 'Hospital total and the nurse-to-bed KPIs'],
          ['Critical area (ICU / ER / OR)', 'Which units count towards KPI A'],
          ['Coverage targets', 'Roster board (eligible / target, shortage), auto-fill'],
        ],
      },
    ],
    callouts: [{ kind: 'info', text: 'A coverage target left empty means "not set" — never zero. Shortages warn but never stop publication. Rest, fatigue and skill-mix rules are not defined by the hospital yet and are not enforced.' }],
    tasks: [
      {
        id: 'units',
        title: 'Add or edit a unit',
        status: 'IMPLEMENTED',
        purpose: 'Keep the list of wards and services correct.',
        who: 'Hospital-wide HR Admin or System Admin.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Workforce → Units → Add unit (or Edit on a row).', 'Code (unique), name, department, description; critical area ICU / ER / OR only for those units.', 'New unit: initial beds. Existing unit: Active on/off.', 'Submit.'],
        result: 'Saved and audited. The hospital total is recalculated live.',
        approval: 'None.',
        next: 'Coverage targets and Requirements for the unit.',
        problems: [{ problem: 'Cannot deactivate', fix: 'The unit still has active employees; move them first.' }],
        related: ['credentials', 'kpi'],
        keywords: ['unit', 'ward', 'add unit', 'critical area', 'icu', 'er', 'or'],
      },
      {
        id: 'beds',
        title: 'Change a unit\'s beds and read the bed history',
        status: 'IMPLEMENTED',
        purpose: 'Record the current bed capacity, with the reason, so the KPIs stay true.',
        who: 'HR Admin or System Admin with the unit in scope. The history: also supervisors.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
        steps: ['Workforce → Units → Change beds on the row.', 'New count (0–500) and a reason.', 'Submit. History shows every change: when, before → after, reason, by whom.'],
        result: 'One history row per change; the history is never edited, which is why it can be trusted in an audit.',
        approval: 'None.',
        next: 'Nursing KPIs use the new count.',
        related: ['kpi'],
        keywords: ['beds', 'bed capacity', 'bed history', 'capacity'],
      },
      {
        id: 'import-units',
        title: 'Import units from a CSV file',
        status: 'IMPLEMENTED',
        purpose: 'Create or update many units at once.',
        who: 'Hospital-wide HR Admin or System Admin.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Workforce → Units → Import CSV.', 'Choose the file or paste it: unit_code, name, department_code, beds, description.', 'Preview: rows created, updated, unchanged, rejected (with reasons).', 'Apply.'],
        result: 'Applied rows are saved; the import never deletes or deactivates a unit. At most 500 rows.',
        approval: 'None.',
        next: 'Check the units list.',
        related: [],
        keywords: ['csv', 'import', 'bulk'],
      },
      {
        id: 'departments',
        title: 'Add or edit a department',
        status: 'IMPLEMENTED',
        purpose: 'Group units into departments (a department scope covers all its units).',
        who: 'Hospital-wide HR Admin or System Admin.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Workforce → Departments → Add department (or Edit).', 'Code, name, description; Active on/off for existing ones.', 'Submit.'],
        result: 'Saved and audited.',
        approval: 'None.',
        next: 'Assign units to it.',
        problems: [{ problem: 'Cannot deactivate', fix: 'It still has active units.' }],
        related: ['roles'],
        keywords: ['department'],
      },
      {
        id: 'positions',
        title: 'Manage positions',
        status: 'IMPLEMENTED',
        purpose: 'Keep the list of position codes (SN, CN, HN …) and whether each can be rostered.',
        who: 'Hospital-wide HR Admin or System Admin.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Workforce → Positions → Add position (or Edit).', 'Code, title, tier, description, display order, Schedulable, Active.', 'Submit.'],
        result: 'Changing Schedulable re-evaluates everyone in the position. Deprecated positions show "→ replacement".',
        approval: 'None.',
        next: 'Eligibility for holders of the position.',
        problems: [{ problem: 'Cannot deactivate', fix: 'Active employees still hold it; change their positions first.' }],
        related: ['nurses', 'eligibility'],
        keywords: ['position', 'schedulable', 'position code', 'deprecated'],
      },
      {
        id: 'rank-grades',
        title: 'Manage the Rank/Grade master',
        status: 'IMPLEMENTED',
        purpose: 'Keep the list of SCFHS nursing classifications (N01 Senior Specialist Consultant Nurse … N05 Health Assistant Nurse to start) that HR chooses from for an employee\'s Rank/Grade and for the SCFHS licence\'s Professional Classification.',
        who: 'Hospital-wide HR Admin or System Admin; everyone else can view the list.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: [
          'Workforce → Rank/Grade. Search by code, classification or meaning; filter All, Active or Inactive.',
          'Add Rank/Grade: code (e.g. N06 — it can never be changed later), SCFHS Nursing Classification, typical meaning, status and sort order. Save.',
          'Edit: change the classification, the meaning, the status or the sort order.',
          'Delete: a record nobody uses is deleted. One assigned to employees or licences cannot be deleted — you are offered Deactivate instead. Reactivate brings an inactive record back.',
        ],
        result: 'The list changes at once, sorted by sort order. An inactive record disappears from new choices but still shows on the employees and licences that use it. Every change (created, updated, deactivated, reactivated, deleted) is in the audit log with the old and new values.',
        approval: 'None.',
        next: 'None.',
        problems: [
          { problem: '"Only system-wide administrators can change the Rank/Grade master"', fix: 'Your HR role covers some units only. Ask a hospital-wide HR Admin or a System Admin.' },
          { problem: 'A code is refused as existing', fix: 'Codes are unique, including inactive records. Reactivate the existing one instead.' },
          { problem: 'Staff with no nursing classification (e.g. administrators)', fix: 'Rank/Grade is required for everyone. Add a record for them, for example N00 — Not applicable (non-nursing), if the hospital agrees.' },
        ],
        related: ['nurses', 'credentials'],
        keywords: ['rank', 'grade', 'rank/grade', 'classification', 'SCFHS classification', 'specialist nurse', 'technician nurse'],
      },
      {
        id: 'specialties',
        title: 'Manage the Nursing Specialty master',
        status: 'IMPLEMENTED',
        purpose: 'Keep the list of nursing specialties (NS001 Clinical Nursing … NS034 General / Unspecified to start) that HR chooses from for an employee\'s Specialty.',
        who: 'Hospital-wide HR Admin or System Admin; everyone else can view the list.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: [
          'Workforce → Specialty. Search by code, name or description; filter All, Active or Inactive.',
          '+ Add Specialty: specialty code (e.g. NS035 — it can never be changed later), name, Arabic name, description, status and sort order. Save.',
          'Edit: change the name, Arabic name, description, status or sort order. The dropdown follows the sort order, not the alphabet.',
          'Deactivate hides a specialty from new employees; Reactivate brings it back.',
          'Delete asks you to confirm. A specialty nobody holds is deleted; one held by employees cannot be deleted — you are offered Deactivate instead.',
        ],
        result: 'The Onboard employee and Edit dropdowns change at once. An inactive specialty still shows on the employees who hold it. Every change (created, updated, deactivated, reactivated, deleted) is in the audit log with the old and new values.',
        approval: 'None.',
        next: 'None.',
        problems: [
          { problem: '"Only system-wide administrators can change the Nursing Specialty master"', fix: 'Your HR role covers some units only. Ask a hospital-wide HR Admin or a System Admin.' },
          { problem: '"A specialty with this name already exists"', fix: 'Names must be unique (capitals do not matter), so the dropdown never shows look-alikes. Edit or reactivate the existing one instead.' },
        ],
        related: ['nurses'],
        keywords: ['specialty', 'speciality', 'nursing specialty', 'ICU', 'NICU', 'emergency', 'midwifery', 'master data'],
      },
      {
        id: 'coverage',
        title: 'Set coverage targets',
        status: 'IMPLEMENTED',
        purpose: 'Set the minimum staff each unit needs per shift (Morning 07–15, Evening 15–23, Night 23–07).',
        who: 'HR Admin or System Admin with the unit in scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Workforce → Coverage targets.', 'Type the number in the unit\'s shift cell; it saves when you leave the cell.', 'Clear a cell to make it "not set".'],
        result: 'The roster board measures each shift against it; auto-fill fills up to it.',
        approval: 'None.',
        next: 'Scheduling.',
        related: ['scheduling', 'kpi'],
        keywords: ['coverage', 'minimum staff', 'target', 'staffing'],
      },
    ],
    keywords: ['workforce', 'organisation', 'structure'],
  },
  {
    id: 'kpi',
    title: 'Nursing KPIs',
    route: '/kpi',
    summary: 'Nurse-to-bed indicators for a date and shift. KPI A rates the ICU, ER and OR critical areas and averages them; KPI B is hospital-wide. Nurses = published roster assignments on that date and shift; beds = active units.',
    audience: 'HR Admin, System Admin, Supervisor',
    roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
    where: 'Side menu → Nursing KPIs.',
    callouts: [{ kind: 'warning', text: 'The band thresholds (Standard, Distress, Failing, Failed) are V03\'s reading of the MoH Ada\'a indicator card, which is not in the repository. The page says so: treat the bands as indicative until the source is confirmed.' }],
    tasks: [
      {
        id: 'read-kpi',
        title: 'Read the nurse-to-bed KPIs',
        status: 'IMPLEMENTED',
        purpose: 'See staffing against beds for a shift.',
        who: 'HR Admin, System Admin, Supervisor.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
        steps: ['Open Nursing KPIs.', 'Choose the date and the shift.', 'KPI A: each critical area with ratio, nurses on duty, beds and code (1–4), and the average band. KPI B: the hospital ratio and band.'],
        result: 'Nothing changes. Only published shifts count — drafts do not.',
        approval: 'None.',
        next: 'Low staffing: Scheduling. Wrong beds or critical areas: Workforce.',
        related: ['workforce', 'scheduling'],
        keywords: ['kpi', 'nurse to bed', 'ratio', 'ada\'a', 'band'],
      },
    ],
    keywords: ['kpi', 'indicator'],
  },
  {
    id: 'scheduling',
    title: 'Roster and scheduling',
    route: '/scheduling',
    summary: 'The weekly roster board of a unit. Supervisors draft shifts from the nurses who are eligible on each date, check coverage, and publish. Eligibility is checked live for every shift date and again at publication. Employees see their own shifts and their home unit\'s published schedule.',
    audience: 'Supervisor (draft and publish their units); HR Admin and System Admin (read); employees (own shifts)',
    roles: ['SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN', 'EMPLOYEE'],
    where: 'Side menu → Roster & Scheduling. Choose a unit and a week.',
    flows: ['roster', 'roster-revalidation'],
    tables: [
      {
        title: 'Reading the board',
        columns: ['You see', 'Meaning'],
        rows: [
          ['3/4 in a cell', 'Eligible published staff / coverage target'],
          ['Target not set', 'No coverage target for that unit and shift'],
          ['Orange −1', 'Published shortage against the target'],
          ['N drafts', 'Drafts not yet published'],
          ['Dashed tag', 'A draft; solid = published'],
          ['Tag colour', 'Green eligible, gold grace, orange policy warning, red ineligible — hover for reasons'],
        ],
      },
    ],
    callouts: [
      { kind: 'info', text: 'A nurse is scheduled only in their home unit, and only once per date and shift across all units. Past dates cannot be drafted or published.' },
      { kind: 'warning', text: 'Auto-fill is a helper, not policy: rest, fatigue and overtime rules are not defined by the hospital and are not checked.' },
    ],
    tasks: [
      {
        id: 'draft-shift',
        title: 'Add a nurse to a shift (draft)',
        status: 'IMPLEMENTED',
        purpose: 'Put an eligible nurse on a shift.',
        who: 'Supervisor of the unit.',
        roles: ['SUPERVISOR'],
        steps: ['Open Roster & Scheduling, choose the unit and the week (‹ › move by a week).', 'Click + in the cell (date × shift).', 'The pool lists the unit\'s nurses with their eligibility for that date and any shifts that day.', 'Click Assign.'],
        result: 'A Draft assignment; the message shows the nurse\'s eligibility for the date.',
        approval: 'None.',
        next: 'Publish the week.',
        problems: [{ problem: 'A nurse is missing from the pool', fix: 'Another unit is their home unit, or they are deleted.' }, { problem: 'Refused: already on a shift', fix: 'One assignment per nurse per date and shift.' }],
        related: ['eligibility'],
        flow: 'roster',
        keywords: ['assign', 'add to shift', 'draft', 'roster pool', 'eligible pool'],
      },
      {
        id: 'auto-fill',
        title: 'Auto-fill the week',
        status: 'IMPLEMENTED',
        purpose: 'Propose drafts up to each shift\'s coverage target.',
        who: 'Supervisor of the unit.',
        roles: ['SUPERVISOR'],
        steps: ['Choose the unit and week, click Auto-fill.', 'Read the proposal: proposed assignments, unfilled shifts, shifts without a target (not filled).', 'Click Create drafts — or Cancel.'],
        result: 'Drafts only — eligible nurses from the unit, fewest shifts first, at most one auto-filled shift per nurse per day.',
        approval: 'None.',
        next: 'Review the drafts and publish.',
        related: ['workforce'],
        flow: 'roster',
        keywords: ['auto fill', 'generate roster', 'automatic'],
      },
      {
        id: 'publish',
        title: 'Publish the roster',
        status: 'IMPLEMENTED',
        purpose: 'Make the week\'s drafts official so nurses see them.',
        who: 'Supervisor of the unit.',
        roles: ['SUPERVISOR'],
        steps: ['Resolve red (ineligible) drafts and gaps.', 'Click Publish week.', 'Read the result: how many were published, which were blocked and why, and how many rely on a grace period or waiver.'],
        result: 'In one step every draft is re-checked for its date: eligible ones are Published; ineligible ones stay Draft with the reasons. Grace or waiver reliance is recorded and audited. Shortages warn but never block.',
        approval: 'None.',
        next: 'Attendance on the day.',
        problems: [{ problem: 'Some drafts stayed Draft', fix: 'Those nurses are ineligible on that date: see the reasons, fix them or choose someone else.' }],
        related: ['eligibility', 'attendance'],
        flow: 'roster',
        keywords: ['publish', 'publish roster', 'release schedule', 'how do i publish a roster'],
      },
      {
        id: 'remove-shift',
        title: 'Remove a draft or cancel a published shift',
        status: 'IMPLEMENTED',
        purpose: 'Take a nurse off a shift.',
        who: 'Supervisor of the unit.',
        roles: ['SUPERVISOR'],
        steps: ['Click the nurse\'s tag in the cell.', 'Draft: confirm removal. Published: give the reason, then confirm.'],
        result: 'Removed (draft) or Cancelled (published, with the reason). Audited.',
        approval: 'None.',
        next: 'Re-staff the shift.',
        related: [],
        keywords: ['remove from shift', 'cancel shift', 'unassign'],
      },
      {
        id: 'returned-to-draft',
        title: 'Handle a shift that returned to draft',
        status: 'IMPLEMENTED',
        purpose: 'React when a published nurse stops being eligible.',
        who: 'Supervisor of the unit (notified automatically).',
        roles: ['SUPERVISOR'],
        steps: ['Open the notice "Published shift returned to draft".', 'Open the week on the board: the shift shows as a red draft.', 'Assign another eligible nurse, or wait for the fix (e.g. a renewal approval) and publish again.'],
        result: 'The roster is valid again once republished.',
        approval: 'None.',
        next: 'Notifications.',
        related: ['notifications', 'eligibility'],
        flow: 'roster-revalidation',
        keywords: ['returned to draft', 'became ineligible after publication'],
      },
      {
        id: 'own-roster',
        title: 'See your own shifts',
        status: 'IMPLEMENTED',
        purpose: 'Know when you work.',
        who: 'Every employee.',
        roles: ['EMPLOYEE'],
        steps: ['Open Roster & Scheduling.', 'My shifts: the next 4 weeks. Below: your home unit\'s published schedule.'],
        result: 'Read only; only published shifts are shown.',
        approval: 'None.',
        next: '—',
        related: ['self-service'],
        keywords: ['my shifts', 'my roster', 'when do i work'],
      },
    ],
    keywords: ['roster', 'schedule', 'shift', 'rota'],
  },
  {
    id: 'attendance',
    title: 'Attendance',
    route: '/attendance',
    summary: 'Planned versus actual: for a unit and date, every published shift with its clock-in and a status. Clock events come from the hospital badge system; nothing is clocked by hand.',
    audience: 'HR Admin, System Admin, Supervisor (unit view); employees (own clock events)',
    roles: ['SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN', 'EMPLOYEE'],
    where: 'Side menu → Attendance. Choose the unit and the date.',
    flows: ['attendance'],
    tables: [
      {
        title: 'Statuses',
        columns: ['Status', 'When', 'Do'],
        rows: [
          ['Upcoming', 'The shift has not started', '—'],
          ['Waiting', 'Started less than 30 minutes ago, no clock-in yet', 'Wait'],
          ['Present', 'Clocked in from 30 minutes before the start', '—'],
          ['Missing', 'No clock-in and 30 minutes have passed since the start', 'Call the nurse; re-staff; a critical alert went to the unit supervisors'],
          ['On duty but ineligible', 'Clocked in, but the nurse is ineligible today', 'Supervisor and HR act at once: read Eligibility, fix or relieve the nurse'],
        ],
      },
    ],
    callouts: [{ kind: 'info', text: 'The badge-system interface is built (the badge system signs in as an API client), but the hospital\'s badge system is not connected yet, so the live server receives no clock events. The Badge simulator (System Admin) is switched off on the live server; it works only where the server setting BADGE_SIMULATOR is on. Manual clocking is not part of V04.' }],
    tasks: [
      {
        id: 'gaps',
        title: 'Check attendance gaps',
        status: 'PARTIAL',
        statusNote: 'The gap view and alerts work; real clock events wait for the hospital badge system to be connected.',
        purpose: 'Find missing or ineligible nurses on shift.',
        who: 'Supervisor, HR Admin, System Admin (scope).',
        roles: ['SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Open Attendance.', 'Choose the unit and date.', 'Read each shift: times, clock-in, status and reasons.'],
        result: 'Nothing changes. The alert job (every 15 minutes) sends one critical notice per missing assignment to the unit\'s supervisors.',
        approval: 'None.',
        next: 'Missing: re-staff in Scheduling. On duty but ineligible: Eligibility.',
        related: ['scheduling', 'eligibility', 'notifications'],
        flow: 'attendance',
        keywords: ['attendance', 'missing', 'clock in', 'badge', 'gap', 'absent', 'late'],
      },
      {
        id: 'own-attendance',
        title: 'See your own clock events',
        status: 'IMPLEMENTED',
        purpose: 'Check what the badge system recorded for you.',
        who: 'Every employee.',
        roles: ['EMPLOYEE'],
        steps: ['Open Attendance: the last 30 days of your clock events (time, event, source).'],
        result: 'Read only.',
        approval: 'None.',
        next: 'A wrong event: tell your supervisor (corrections are not in V04).',
        related: ['self-service'],
        keywords: ['my attendance', 'my clock'],
      },
    ],
    keywords: ['attendance', 'badge', 'pacs'],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    route: '/notifications',
    summary: 'Your action queue: each notice tells you something needs you — a credential or contract nearing its end, a shift returned to draft, a missing nurse, a request to answer. The bell at the top shows how many are unread.',
    audience: 'Everyone (own notices only)',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    where: 'The bell at the top, or Side menu → Notifications.',
    flows: ['reminders'],
    tables: [
      {
        title: 'Notices the system sends',
        columns: ['Notice', 'Who receives it', 'Do'],
        rows: [
          ['Credential expiring soon / Credential expired', 'Holder; then supervisor and HR as it gets closer', 'Renew (My Credentials); HR decides the renewal'],
          ['Contract ending soon / Contract ended', 'Employee and HR; supervisor from 14 days', 'HR renews the contract'],
          ['Renewal Required — Grace Period Active / Grace period in use', 'Holder / HR in scope, when grace is first used', 'Decide the renewal before grace ends'],
          ['Grace period ended without renewal', 'HR in scope', 'The nurse is ineligible now: renew or re-staff'],
          ['New credential requirement', 'Nurses affected by a new transition requirement', 'Obtain the credential before the deadline'],
          ['Published shift returned to draft', 'Unit supervisors', 'Re-staff the shift'],
          ['Critical coverage alert: not clocked in / ineligible nurse on duty', 'Unit supervisors', 'Call the nurse; re-staff; check Eligibility'],
          ['SCFHS: <credential> of <nurse>', 'HR in scope', 'Check the record against SCFHS'],
          ['Personal data request', 'HR', 'Work it in Data protection'],
          ['Break-glass account activated', 'The recipients configured for break-glass alerts', 'Verify the emergency'],
          ['Eligibility drift corrected; Document storage problem', 'System administrators', 'Review Background jobs'],
        ],
      },
    ],
    callouts: [{ kind: 'info', text: 'Each notice is in the app; when the hospital\'s e-mail is on, a copy goes to your e-mail too, and a short Telegram message ("something is waiting", never the details) if you linked Telegram. Approval requests are not sent as notifications: check Approvals.' }],
    tasks: [
      {
        id: 'read-notifications',
        title: 'Read and clear notifications',
        status: 'IMPLEMENTED',
        purpose: 'Work through what needs you.',
        who: 'Everyone.',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Click the bell or open Notifications. Unread is shown first; switch to All for history.', 'Read the priority (Critical, High, Medium, Low), title and message (Arabic when the page is in Arabic).', 'Act on it, then Mark read — or Mark all read.'],
        result: 'Read notices leave the unread count; they stay in All.',
        approval: 'None.',
        next: 'The page the notice is about.',
        related: ['credentials', 'contracts', 'scheduling'],
        flow: 'reminders',
        keywords: ['notification', 'bell', 'unread', 'mark read', 'alert', 'reminder'],
      },
    ],
    keywords: ['notification', 'alert', 'reminder'],
  },
];
