import type { GuideSection } from '../types';

export const OVERVIEW: GuideSection[] = [
  {
    id: 'hospital-workflow',
    title: 'How the hospital system works',
    summary: 'The complete flow, from the hospital\'s master data to the nurse on the ward. Each stage depends on the one before it: a nurse with no approved contract or no verified required credential is ineligible, and an ineligible nurse cannot be published on the roster.',
    audience: 'Everyone',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    flows: ['hospital-workflow', 'onboarding', 'eligibility-engine', 'roster'],
    tables: [
      {
        title: 'Stage by stage',
        columns: ['Stage', 'Who', 'Where', 'Done when'],
        rows: [
          ['1. Departments, units, beds', 'HR (hospital-wide)', 'Workforce, or Hospital baseline import', 'Units and beds match the hospital'],
          ['2. Positions', 'HR (hospital-wide)', 'Workforce → Positions', 'Schedulable flags are right'],
          ['3. Credential catalogue', 'HR + a second approver', 'Credentials → Catalog / Categories', 'Types approved'],
          ['4. Requirements', 'HR', 'Credentials → Requirements', 'Every unit\'s policy entered'],
          ['5. Nurse onboarded', 'HR', 'Nurses → Onboard employee', 'Employee and Draft contract exist'],
          ['6. Contract approved', 'HR + a second HR person', 'Contracts', 'Approved or Active'],
          ['7. Credentials and evidence', 'Nurse (or HR)', 'My Credentials', 'Recorded with documents'],
          ['8. Verification / SCFHS', 'HR', 'Credentials → Review queue', 'Valid or Expiring soon'],
          ['9. Eligibility', 'System', 'Eligibility', 'ELIGIBLE (or grace / warning)'],
          ['10. Coverage targets', 'HR', 'Workforce → Coverage targets', 'Each shift has a target'],
          ['11. Roster published', 'Supervisor', 'Roster & Scheduling', 'Week published'],
          ['12. Attendance', 'Badge system', 'Attendance', 'Clock-ins match the roster'],
          ['13. Monitoring and notices', 'System → everyone', 'Nursing KPIs, Notifications', 'Each notice acted on'],
          ['14. Audit and governance', 'System Admin', 'Audit & Compliance', 'Chain verified'],
        ],
      },
    ],
    tasks: [],
    keywords: ['workflow', 'process', 'how it works', 'overview', 'end to end', 'flow'],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    summary: 'Common questions and what to do. When reporting a problem, give the page, what you clicked, the exact message and the time — the administrators can find the request in the log.',
    audience: 'Everyone',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    tables: [
      {
        title: 'Questions',
        columns: ['Question', 'Answer'],
        rows: [
          ['Why can\'t I see a nurse?', 'The nurse is outside your scope, or the record was deleted. Supervisors see only their units.'],
          ['Why is a nurse ineligible?', 'Open Eligibility and read the red reasons; fix the source record (see Eligibility → Resolve an ineligible nurse).'],
          ['Why is a menu item missing?', 'Your role does not include it. System Admins: elevate first.'],
          ['Why is there no Approve button?', 'You created or submitted the item; a different administrator must approve.'],
          ['The nurse cannot be added to a shift', 'Not eligible on that date, not in this home unit, or already on a shift that day.'],
          ['Published shifts went back to draft', 'A nurse stopped being eligible; re-staff the shift.'],
          ['My upload is refused', 'PDF, JPEG, PNG or WebP (contracts: PDF), at most 10 MB, and it must pass the virus scan.'],
          ['I cannot open a document', 'Only clean files open, only for the holder and HR; supervisors never see documents. The link is single-use: click again.'],
          ['Send invitation fails', 'E-mail must be on, the nurse needs an approved contract and a valid contact e-mail not used by another account.'],
          ['Sign-in is refused or paused', 'Wrong password 5 times pauses the account for up to 15 minutes. Use Forgot password? (staff) or ask HR.'],
          ['I lost my phone', 'Use a recovery code, or ask HR to reset two-factor sign-in.'],
          ['ELIGIBLE but nothing was checked', 'The unit has no requirements configured (grey note): HR must enter the unit\'s policy.'],
          ['KPI looks wrong', 'Only published shifts count; check beds and critical areas in Workforce.'],
          ['Attendance shows everyone missing', 'The badge system is not connected yet; real clock-ins will appear once it is.'],
        ],
      },
      {
        title: 'Messages you may see',
        columns: ['Message contains', 'Meaning'],
        rows: [
          ['SCOPE_NOT_COVERED / outside your assigned scope', 'The record is in a unit or department you do not cover'],
          ['SELF_… (own record, own contract, own credential)', 'Separation of duties: someone else must do it'],
          ['…APPROVAL… / different administrator', 'A second person must approve'],
          ['EMAIL_OFF / e-mail is not configured', 'E-mail is switched off on this system'],
          ['DOCUMENT_NOT_CLEAN', 'The file did not pass scanning'],
          ['TRANSITION_NOT_ALLOWED', 'That action does not apply to the record\'s current status'],
        ],
      },
    ],
    tasks: [],
    keywords: ['problem', 'error', 'help', 'not working', 'refused', 'faq', 'why'],
  },
  {
    id: 'quick-reference',
    title: 'Quick reference',
    summary: 'Statuses, codes and limits on one page.',
    audience: 'Everyone',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    tables: [
      {
        title: 'Limits and timings',
        columns: ['Item', 'Value'],
        rows: [
          ['Password', '12–72 characters'],
          ['Sign-in pause', '5 wrong attempts per account, or 20 per network, within 15 minutes'],
          ['Invitation link', '72 hours, works once'],
          ['Password reset link', '30 minutes (self-service); 24 hours (sent by HR)'],
          ['Sign-in e-mail change link', '30 minutes'],
          ['Document upload', 'PDF / JPEG / PNG / WebP, at most 10 MB; contracts PDF only'],
          ['Document link', 'Single-use, 60 seconds'],
          ['Credential "Expiring soon"', 'Within 60 days of expiry'],
          ['Grace days', '0–90 per credential type (hospital policy)'],
          ['Emergency waiver', 'One credential type, at most 72 hours'],
          ['Role expiry', 'Supervisor ≤ 90 days; HR Admin and System Admin ≤ 365 days'],
          ['System Admin elevation', '1–4 hours'],
          ['Shifts (Riyadh time)', 'Morning 07:00–15:00, Evening 15:00–23:00, Night 23:00–07:00'],
          ['Missing clock-in', '30 minutes after the start; alerts every 15 minutes'],
          ['Personal-data request', 'Answered within 30 days; package available 30 days'],
          ['Request log kept', '365 days'],
        ],
      },
      {
        title: 'Daily jobs (Riyadh time)',
        columns: ['Time', 'Job'],
        rows: [
          ['00:05', 'Daily transition: contract and credential statuses by date, grace and transition deadlines'],
          ['02:30 / 02:40', 'Request-log and simulated-Telegram purges'],
          ['03:00', 'Consistency audit: stored eligibility checked against the engine'],
          ['04:30', 'Document vault check'],
          ['05:00', 'SCFHS sync (nightly licence checks)'],
          ['06:00', 'Expiry scan: credential and contract reminders'],
          ['Every 15 minutes', 'Attendance alerts'],
        ],
      },
      {
        title: 'Status colours',
        columns: ['Colour', 'Means'],
        rows: [
          ['Green', 'Valid, Active, Eligible, Present'],
          ['Gold / amber', 'Expiring soon, grace, policy warning, pending'],
          ['Orange', 'Pending approval, shortage'],
          ['Red', 'Expired, Ineligible, Missing, blocking reason'],
          ['Grey', 'Note, inactive, not set'],
        ],
      },
    ],
    tasks: [],
    keywords: ['reference', 'limits', 'codes', 'cheat sheet', 'timings', 'jobs'],
  },
];
