import type { GuideSection } from '../types';

export const PEOPLE: GuideSection[] = [
  {
    id: 'nurses',
    title: 'Nurses',
    route: '/nurses',
    summary: 'The staff master record: one row per employee with job number, name, unit, position, contact details and employment fields. Onboarding creates the record together with its first (Draft) contract. Everything else — contracts, credentials, eligibility, rosters — hangs off this record.',
    audience: 'HR Admin and System Admin (all fields, within scope); Supervisor (their units, private fields hidden)',
    roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
    where: 'Side menu → Nurses. Click a row to open the record.',
    flows: ['onboarding'],
    tables: [
      {
        title: 'Who can change which field',
        columns: ['Field', 'Who changes it', 'Notes'],
        rows: [
          ['First, middle, last name', 'HR / System Admin', 'Full name is built by the system, never typed'],
          ['Job number', 'HR / System Admin', 'Unique (case does not matter); no format rule'],
          ['Job title, file no., actual work place, marital status, salary (SAR), hire date', 'HR / System Admin', 'Hidden from supervisors: salary, marital status, nationality, rank, file number, job post location, emergency contact'],
          ['Nationality', 'HR / System Admin', 'Required. Chosen from the standard list (type to search by nationality, country or code); free text is not accepted. Hidden from supervisors'],
          ['Job Post (City)', 'HR / System Admin', 'Required. Region + City, chosen in the Select Job Post Location window (region first, then a city of that region) from Workforce → Locations; shown as "Qassim Region - Buraydah"; free text is not accepted. Hidden from supervisors'],
          ['Specialty', 'HR / System Admin', 'Required. Chosen from the Nursing Specialty master (Workforce → Specialty), in its sort order; type to search by code, name or description; free text is not accepted. Supervisors see it'],
          ['Rank/Grade (SCFHS classification)', 'HR / System Admin', 'Required. Chosen in the Select Rank/Grade window from the Rank/Grade master (Workforce → Rank/Grade); free text is not accepted. Hidden from supervisors'],
          ['Unit', 'HR / System Admin', 'Moving a nurse re-checks eligibility and returns invalid future shifts to Draft'],
          ['Position', 'HR Admin only (Change position)', 'Needs a reason; recorded from → to; a position never gives a login role'],
          ['Contact e-mail', 'HR / System Admin', 'Used for the login invitation'],
          ['Mobile and emergency contact phone', 'HR, and the employee on My Profile', 'International format, e.g. +966500000000'],
        ],
      },
    ],
    callouts: [{ kind: 'info', text: 'A new nurse cannot be scheduled until another HR administrator approves the contract created at onboarding.' }],
    tasks: [
      {
        id: 'find-nurse',
        title: 'Find and open a nurse',
        status: 'IMPLEMENTED',
        purpose: 'Look up a staff record.',
        who: 'HR Admin, System Admin, Supervisor — only nurses in their scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR'],
        steps: ['Open Nurses.', 'Type a job number or name in the search box and press Enter, or filter by unit.', 'Click the row to open the record on the right.'],
        result: 'Nothing changes. HR sees every field; supervisors see the baseline view.',
        approval: 'None.',
        next: 'Contracts, Credentials or Eligibility for the same nurse.',
        problems: [{ problem: 'The nurse is not listed', fix: 'The nurse is outside your scope, or the record was deleted. Ask HR.' }],
        related: ['contracts', 'credentials', 'eligibility'],
        keywords: ['search nurse', 'employee', 'staff', 'look up'],
      },
      {
        id: 'onboard',
        title: 'Onboard a new nurse',
        status: 'IMPLEMENTED',
        purpose: 'Create the employee and the first contract in one step.',
        who: 'HR Admin or System Admin, for a unit in scope (or Unassigned).',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['Name, job number, contact e-mail, nationality, specialty, Rank/Grade (SCFHS classification), Job Post (City); the employment contract type and the contract start and end dates.', 'Unit and position if known — the defaults are Unassigned and SN.'],
        steps: [
          'Open Nurses and click Onboard employee.',
          'Fill in the details and choose the Employment Contract Type. The Hijri date is shown under each contract date.',
          'Choose the unit (or leave Unassigned) and the position.',
          'Click Submit.',
        ],
        result: 'The employee and a Draft contract are created together (all or nothing), audited as high priority. Eligibility is INELIGIBLE until the contract is approved.',
        approval: 'The contract must be approved by a different HR administrator (Contracts).',
        next: 'Contracts: upload the signed copy and Submit. Then record credentials.',
        problems: [
          { problem: 'The job number is refused as a duplicate', fix: 'Job numbers are unique regardless of case. Search for the existing record.' },
          { problem: 'The form asks for a position', fix: 'The hospital has no active SN position to default to; choose one.' },
          { problem: '"Nationality is required."', fix: 'Choose it from the list: type a few letters of the nationality (Filipino), the country (Philippines) or the code (PHL).' },
          { problem: '"Job Post (City) is required."', fix: 'Click the field (or its search button): choose the Region / Province, then the City — Select becomes available once both are chosen.' },
          { problem: '"Specialty is required."', fix: 'Choose it from the list: type part of the name or code (ICU, NICU, NS013). If the right one is missing, a hospital-wide HR Admin adds it under Workforce → Specialty; meanwhile Other Nursing Specialty or General / Unspecified can be chosen.' },
          { problem: '"Rank/Grade is required."', fix: 'Click the Rank/Grade field (or its search button), find the classification by code, name or meaning, and double-click it or click Select.' },
        ],
        related: ['contracts', 'credentials', 'eligibility'],
        flow: 'onboarding',
        keywords: ['add nurse', 'new employee', 'hire', 'create staff', 'onboarding'],
      },
      {
        id: 'edit-nurse',
        title: 'Edit a staff record',
        status: 'IMPLEMENTED',
        purpose: 'Correct or update employee details, or move a nurse to another unit.',
        who: 'HR Admin or System Admin within scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Open the nurse.', 'Click Edit at the top of the panel.', 'Change the fields and click Submit.'],
        result: 'Saved and audited. A unit change re-evaluates eligibility; future published shifts that are no longer valid return to Draft and the supervisors are told.',
        approval: 'None.',
        next: 'Check Eligibility if the unit changed.',
        problems: [
          { problem: 'Phone refused', fix: 'Use the international format: + then country code and number, e.g. +966500000000.' },
          { problem: 'Nationality shows "not on the nationality list"', fix: 'It was typed in before the list existed and matched no listed nationality. Edit the record: the old text is shown under the field; choose the matching nationality and save.' },
          { problem: 'Job Post (City) shows "not on the location list"', fix: 'Text typed in before the location list that is not exactly a listed city (e.g. "Riyadh - Al Iman Hospital"). Edit the record: the old text is shown under the field; choose the Region + City and save.' },
          { problem: 'Specialty shows "not on the specialty list" (e.g. "Surgical")', fix: 'Text typed in before the specialty list that could not be matched safely (Surgical could be Medical-Surgical or Operating Room). Edit the record: the old text is shown under the field; choose the specialty and save.' },
          { problem: 'Rank/Grade shows "not on the Rank/Grade list" (e.g. "Grade 7")', fix: 'A pay grade or other text typed in before the Rank/Grade master. Edit the record: the old text is shown under the field; choose the SCFHS classification and save.' },
        ],
        related: ['eligibility', 'scheduling'],
        keywords: ['update nurse', 'change unit', 'move nurse', 'transfer', 'nationality'],
      },
      {
        id: 'change-position',
        title: 'Change a nurse\'s position',
        status: 'IMPLEMENTED',
        purpose: 'Record a new position (for example SN → CN).',
        who: 'HR Admin only (not System Admin).',
        roles: ['HR_ADMIN'],
        steps: ['Open the nurse.', 'Click Change position.', 'Choose the position and write the reason.', 'Submit.'],
        result: 'Recorded from → to with the reason. Eligibility is re-evaluated (a non-schedulable position cannot be rostered).',
        approval: 'None.',
        next: 'Requirements may differ by position: check Eligibility.',
        problems: [{ problem: 'Refused', fix: 'The position is inactive or unchanged.' }],
        related: ['workforce', 'eligibility'],
        keywords: ['promotion', 'position', 'grade change'],
      },
      {
        id: 'delete-nurse',
        title: 'Delete a staff record',
        status: 'IMPLEMENTED',
        purpose: 'Remove a nurse who left, keeping the history.',
        who: 'HR Admin or System Admin within scope; never on their own record.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Open the nurse.', 'Click Delete.', 'Write the reason (at least 10 characters) and confirm.'],
        result: 'A soft delete: the record leaves the lists, history stays, eligibility becomes INELIGIBLE.',
        approval: 'None.',
        next: 'Deactivate the login account in Nursing Administration → Accounts if there is one.',
        related: ['administration'],
        keywords: ['remove nurse', 'resign', 'terminate employee'],
      },
      {
        id: 'invite',
        title: 'Send a login invitation',
        status: 'IMPLEMENTED',
        purpose: 'Let the nurse create their own login with a private link.',
        who: 'HR Admin or System Admin within scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['E-mail switched on by the hospital.', 'An Approved or Active contract.', 'A valid contact e-mail on the record, not used by another account.'],
        steps: ['Open the nurse.', 'Scroll to Login account.', 'Click Send invitation.'],
        result: 'A private link is e-mailed (valid 72 hours, works once). A new invitation cancels the previous link.',
        approval: 'None.',
        next: 'The nurse creates the account (Getting started → Create your account from an invitation).',
        problems: [
          { problem: '"E-mail is not configured"', fix: 'E-mail is switched off: create the account in Nursing Administration → Accounts instead.' },
          { problem: '"current approved or active contract"', fix: 'Approve the contract first.' },
          { problem: '"already has a login account" / "e-mail in use"', fix: 'Use Accounts to manage the existing login.' },
        ],
        related: ['getting-started', 'administration', 'contracts'],
        flow: 'invitation',
        keywords: ['invitation', 'login account', 'create login', 'send invite'],
      },
    ],
    keywords: ['staff', 'employee', 'master data', 'personnel'],
  },
  {
    id: 'contracts',
    title: 'Contracts',
    route: '/contracts',
    summary: 'Employment contracts. A nurse is covered — and can be eligible — only on dates inside an Approved or Active contract. HR prepares a contract, attaches the signed copy and submits it; a different HR administrator approves it.',
    audience: 'HR Admin and System Admin (create, approve, change); Supervisor (reduced view); employees (their own)',
    roles: ['HR_ADMIN', 'SYSTEM_ADMIN', 'SUPERVISOR', 'EMPLOYEE'],
    where: 'Side menu → Contracts.',
    flows: ['contract-lifecycle', 'contract-dates'],
    tables: [
      {
        title: 'Contract statuses',
        columns: ['Status', 'Covers dates?', 'Meaning'],
        rows: [
          ['Draft', 'No', 'Being prepared; can be submitted once the signed copy is uploaded'],
          ['Pending approval', 'No', 'Submitted; waits for a different HR administrator'],
          ['Approved', 'Yes, from its start date', 'Approved for a future period'],
          ['Active', 'Yes', 'Approved and covering today'],
          ['Suspended', 'No', 'Paused with a reason; can be reinstated'],
          ['Terminated', 'No', 'Ended early; final'],
          ['Expired', 'No', 'The end date passed (set by the daily job)'],
          ['Superseded', 'No', 'Replaced; never set by hand'],
        ],
      },
      {
        title: 'Actions and who may take them',
        columns: ['Action', 'From', 'Result', 'Rule'],
        rows: [
          ['Submit', 'Draft', 'Pending approval', 'A clean signed copy (PDF) must be uploaded'],
          ['Return', 'Pending approval', 'Draft', 'Reason required'],
          ['Approve', 'Pending approval', 'Active (covers today) or Approved', 'Not the person who created or submitted it'],
          ['Suspend', 'Approved, Active', 'Suspended', 'Reason required'],
          ['Reinstate', 'Suspended', 'Approved or Active by date', 'Reason required; overlap re-checked'],
          ['Terminate', 'Approved, Active', 'Terminated (final)', 'Reason required'],
        ],
      },
    ],
    callouts: [
      { kind: 'warning', text: 'Nobody can create, renew, change or upload to their own contract, and nobody approves a contract they created or submitted.' },
      { kind: 'info', text: 'Two Approved/Active periods of one nurse may never overlap. Every contract change re-evaluates the nurse\'s eligibility at once.' },
      { kind: 'info', text: 'Every new contract and renewal names an Employment Contract Type from the hospital\'s list (Contract types). It is information only: it does not change eligibility, the renewal rule or approval. Contracts created before the field existed show "Not classified".' },
      { kind: 'warning', text: 'A renewal needs valid credentials. For a nurse who has had a contract before, a contract is neither created nor approved while a required credential of their unit and position is missing, expired, not yet verified, suspended or revoked. The ended contract itself does not count, so an expired contract can always be renewed once the credentials are in order. A nurse\'s first contract is not checked.' },
    ],
    tasks: [
      {
        id: 'new-contract',
        title: 'Create a contract',
        status: 'IMPLEMENTED',
        purpose: 'Give a nurse without a covering contract a new employment period.',
        who: 'HR Admin or System Admin within scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['The employment contract type, start and end dates.', 'The signed contract as a PDF.'],
        steps: ['Open Contracts and click New contract.', 'Search the employee by job number or name (only nurses with no Approved/Active contract are offered).', 'Choose the Employment Contract Type (required; only active types are offered).', 'Choose the start and end dates (the Hijri dates are shown).', 'Click Submit — the contract is saved as Draft.'],
        result: 'A Draft contract. It gives no coverage yet.',
        approval: 'Approval by a different HR administrator comes after Submit.',
        next: 'Upload the signed copy, then Submit (next task).',
        problems: [
          { problem: 'The employee is not offered', fix: 'They already have an Approved or Active contract: use Renew contract.' },
          { problem: '"Employment Contract Type is required."', fix: 'Choose a type. If the right one is missing, a system-wide HR Admin or System Admin adds it under Contract types.' },
          { problem: '"Renew or verify these credentials before renewing the contract"', fix: 'The nurse had a contract before, so this counts as a renewal: the credentials listed must be valid first (see Renew a contract).' },
        ],
        related: ['nurses', 'eligibility'],
        flow: 'contract-lifecycle',
        keywords: ['new contract', 'create contract', 'employment'],
      },
      {
        id: 'renew-contract',
        title: 'Renew a contract',
        status: 'IMPLEMENTED',
        purpose: 'Prepare the next period so the nurse stays covered without a gap.',
        who: 'HR Admin or System Admin within scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['Every required credential of the nurse\'s unit and position is valid: verified, in date, not suspended or revoked (a credential in its grace period, under a waiver or in a transition period also passes). Check Eligibility: only credential reasons matter here, not the contract reason.'],
        steps: ['Open Contracts and click Renew contract.', 'Choose the employee: the current contract is shown, and the dates (the day after the current end, same length) and the Employment Contract Type are pre-filled from it.', 'Adjust the dates or the type if needed and Submit. A contract from before the type existed has none: choose one.'],
        result: 'A new Draft contract for the next period. Refused with the list of credentials to renew or verify first if any required credential is not valid — checked again when the contract is approved.',
        approval: 'After Submit, a different HR administrator approves.',
        next: 'Upload the copy and Submit. Once approved, the nurse gets no contract reminders for the old period.',
        problems: [
          { problem: 'A nurse is missing from the renewal list', fix: 'The list shows at most 500 employees in your scope; type to search.' },
          { problem: '"Renew or verify these credentials before renewing the contract: …"', fix: 'The nurse renews the listed credentials on My Credentials and HR verifies them (or approves the renewals); then renew the contract. A nurse with no unit is refused too, because no credential can be checked: assign the unit first.' },
          { problem: 'Approve refused with the same message', fix: 'A credential expired or was suspended after the renewal was created. Bring it back in order, then approve.' },
        ],
        related: ['eligibility', 'notifications'],
        flow: 'contract-lifecycle',
        keywords: ['renew contract', 'extend', 'next period'],
      },
      {
        id: 'contract-types',
        title: 'Manage employment contract types',
        status: 'IMPLEMENTED',
        purpose: 'Keep the list of employment contract types that HR chooses from on a new contract, a renewal or an onboarding.',
        who: 'HR Admin or System Admin with system-wide scope (a unit-scoped HR Admin can only choose from the list).',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: [
          'Open Contracts and click Contract types.',
          'Add contract type: a code (A–Z, digits and _, at most 20 — it cannot be changed later), the English name, the Arabic name and the display order.',
          'Edit: change the names or the order, or switch a type Active again.',
          'Delete: confirm. A type that no contract uses is deleted; a type that contracts already use is deactivated instead.',
        ],
        result: 'The list changes at once and every change is in the audit log. A deactivated type disappears from new contracts but stays on the contracts that use it, so old records keep their meaning.',
        approval: 'None — the type is information only and changes no rule.',
        next: 'None.',
        problems: [
          { problem: '"Only system-wide administrators can change the employment contract types"', fix: 'Your HR role covers some units only. Ask a system-wide HR Admin or a System Admin.' },
          { problem: 'Delete only deactivated the type', fix: 'Contracts use it (see the Contracts column). That is intended: the old contracts keep showing it.' },
          { problem: 'A contract type code is refused as existing', fix: 'Codes are unique, including deactivated types. Edit the existing type and switch it Active instead.' },
        ],
        related: ['administration'],
        keywords: ['contract type', 'employment type', 'MOH', 'agency', 'outsourcing', 'manpower', 'temporary', 'SOP', 'direct hire'],
      },
      {
        id: 'contract-copy',
        title: 'Upload the signed contract copy',
        status: 'IMPLEMENTED',
        purpose: 'Attach the signed document; it is required before Submit.',
        who: 'HR Admin or System Admin within scope (view: also the employee).',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['On the contract row click Contract copy.', 'Click Upload signed copy and choose the PDF (at most 10 MB).', 'Wait until it is listed as CLEAN.'],
        result: 'A new version is stored encrypted; earlier versions are never overwritten. Files that fail the virus scan are refused.',
        approval: 'None.',
        next: 'Submit the contract.',
        problems: [{ problem: 'Upload refused', fix: 'Only PDF, at most 10 MB, and the file must pass the virus scan.' }],
        related: ['credentials'],
        keywords: ['upload contract', 'signed copy', 'pdf'],
      },
      {
        id: 'submit-approve-contract',
        title: 'Submit and approve a contract',
        status: 'IMPLEMENTED',
        purpose: 'Move a Draft contract to Approved / Active so it covers the nurse.',
        who: 'Submit: HR Admin or System Admin. Approve: a different HR person in scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Person A: on the Draft row click Submit → Pending approval.', 'Person B (did not create or submit it): open the contract copy and check it.', 'Person B: click Approve — or Return with a reason to send it back to Draft.'],
        result: 'Approve: Active if it covers today, otherwise Approved. A message shows the new status and the nurse\'s eligibility.',
        approval: 'This is the approval (not through the Approvals tab).',
        next: 'Credentials, then Eligibility.',
        problems: [
          { problem: '"must be approved by a different HR administrator"', fix: 'You created or submitted it. Ask another HR administrator.' },
          { problem: '"Upload the signed contract copy"', fix: 'Upload the PDF and wait for CLEAN before Submit.' },
          { problem: '"period has already ended" / overlap', fix: 'Correct the dates: periods may not overlap and must not be in the past.' },
        ],
        related: ['eligibility', 'approvals'],
        flow: 'contract-lifecycle',
        keywords: ['approve contract', 'submit contract', 'return contract', 'pending approval'],
      },
      {
        id: 'suspend-terminate-contract',
        title: 'Suspend, reinstate or terminate a contract',
        status: 'IMPLEMENTED',
        purpose: 'Stop coverage temporarily or for good.',
        who: 'HR Admin or System Admin within scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['On the contract row click Suspend, Reinstate or Terminate.', 'Write the reason (at least 5 characters) and submit.'],
        result: 'Suspended and Terminated contracts cover nothing: the nurse becomes ineligible and invalid future shifts return to Draft. Reinstate restores Approved or Active by date.',
        approval: 'None.',
        next: 'Tell the supervisor; re-staff affected shifts.',
        related: ['scheduling', 'eligibility'],
        keywords: ['suspend contract', 'terminate', 'end contract', 'reinstate'],
      },
    ],
    keywords: ['contract', 'employment', 'coverage'],
  },
];
