import type { GuideSection } from '../types';

export const SELF: GuideSection[] = [
  {
    id: 'self-service',
    title: 'Employee self-service',
    route: '/my-credentials',
    summary: 'What every nurse can do for themselves: see their profile and keep their phone numbers current, add and renew credentials with evidence, see their own eligibility, contract, shifts and clock-ins, and make personal-data requests.',
    audience: 'Every account linked to a staff record',
    roles: ['EMPLOYEE'],
    where: 'Side menu → My Profile, My Credentials, My data; also Contracts, Roster & Scheduling and Attendance show your own records.',
    flows: ['credential-new', 'credential-renewal', 'pdpl-request'],
    tasks: [
      {
        id: 'my-profile',
        title: 'Check your profile and update your phones',
        status: 'IMPLEMENTED',
        purpose: 'Keep your contact numbers current so your unit can reach you.',
        who: 'Every employee, for their own record.',
        roles: ['EMPLOYEE'],
        steps: ['Open My Profile: job number, name, unit, position, job title, contact e-mail.', 'Under My phone numbers, enter the mobile and emergency contact numbers in international format (+966…).', 'Submit.'],
        result: 'Saved. Every other field is maintained by HR.',
        approval: 'None.',
        next: 'Anything else wrong: ask HR, or make a correction request on My data.',
        related: ['nurses'],
        keywords: ['profile', 'phone', 'mobile', 'emergency contact', 'my details'],
      },
      {
        id: 'my-credentials',
        title: 'Add a credential and upload its evidence',
        status: 'IMPLEMENTED',
        purpose: 'Put your licence or certificate on record so it counts for your eligibility.',
        who: 'Every employee, for their own credentials.',
        roles: ['EMPLOYEE'],
        before: ['The document (PDF, JPEG, PNG or WebP, at most 10 MB) and its details.'],
        steps: [
          'Open My Credentials. At the top: your eligibility and any required credential you are missing (red box).',
          'Click Add credential, choose the type, fill in the details (the form follows the type) and Submit.',
          'On the new row click Evidence → Upload evidence and choose the file.',
        ],
        result: '"Submitted — HR will verify it." The credential is Pending verification until HR verifies it.',
        approval: 'HR verifies.',
        next: 'Watch My Credentials and Notifications.',
        problems: [{ problem: 'Upload refused', fix: 'Use PDF, JPEG, PNG or WebP under 10 MB; the file must pass the virus scan.' }],
        related: ['credentials'],
        flow: 'credential-new',
        keywords: ['add credential', 'upload certificate', 'my licence', 'how do i add a credential'],
      },
      {
        id: 'my-renewal',
        title: 'Renew your credential',
        status: 'IMPLEMENTED',
        purpose: 'Submit your renewed licence or certificate before (or after) it expires.',
        who: 'Every employee, for their own credentials.',
        roles: ['EMPLOYEE'],
        before: ['The renewed details with the new expiry date, and the new document.'],
        steps: ['My Credentials → Renew on the credential.', 'Enter the new details and Submit.', 'Evidence → Upload evidence: the new document.', 'The row shows "Renewal under review".'],
        result: 'Your current credential stays valid until its own expiry while HR reviews. If it already expired and the type has grace days, a yellow "Renewal Required — Grace Period Active" banner shows while grace runs.',
        approval: 'HR approves or rejects.',
        next: 'Notifications tell you the outcome; My Credentials shows the new status.',
        related: ['credentials', 'eligibility'],
        flow: 'credential-renewal',
        keywords: ['renew', 'renew my license', 'renew licence', 'how do i renew a license', 'expired'],
      },
      {
        id: 'my-data',
        title: 'Make a personal-data request',
        status: 'IMPLEMENTED',
        purpose: 'Exercise your rights under the Personal Data Protection Law.',
        who: 'Every employee.',
        roles: ['EMPLOYEE'],
        steps: ['My data → New request.', 'Type: Access (a copy), Portability (machine-readable), Correction (say what is wrong — 10+ characters), Erasure (identity numbers and scans).', 'Submit, then follow the status; download the package when it is ready (available 30 days).'],
        result: 'HR answers within 30 days. Employment records the hospital must keep by law are not erased.',
        approval: 'HR; erasure by a System Admin.',
        next: '—',
        related: ['administration'],
        flow: 'pdpl-request',
        keywords: ['my data', 'pdpl', 'privacy', 'copy of my data', 'delete my data'],
      },
      {
        id: 'my-other',
        title: 'Your contract, shifts and clock-ins',
        status: 'IMPLEMENTED',
        purpose: 'See your own employment, roster and attendance records.',
        who: 'Every employee.',
        roles: ['EMPLOYEE'],
        steps: ['Contracts: your contracts and the signed copy.', 'Roster & Scheduling: your next 4 weeks and your home unit\'s published schedule.', 'Attendance: your clock events of the last 30 days.'],
        result: 'Read only.',
        approval: 'None.',
        next: 'Questions: your supervisor or HR.',
        related: ['contracts', 'scheduling', 'attendance'],
        keywords: ['my contract', 'my schedule', 'my shifts'],
      },
    ],
    keywords: ['self service', 'employee', 'my'],
  },
  {
    id: 'security',
    title: 'Security and your account',
    route: '/security',
    summary: 'Keep your account safe: password, two-factor sign-in with an authenticator app and recovery codes, your sign-in e-mail, Telegram, and your sign-in history. System Admins also use elevation here.',
    audience: 'Everyone',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    where: 'Your name at the top right → Change password, Sign-in history, Two-factor sign-in.',
    flows: ['pam'],
    callouts: [
      { kind: 'warning', text: 'Two-factor sign-in is required for Supervisor, HR Admin and System Admin. Keep the 10 recovery codes on paper, privately; each works once.' },
      { kind: 'info', text: 'The break-glass account is for emergencies only: it does not use two-factor sign-in and every use alerts hospital leadership. Do not use it for ordinary work or tests.' },
    ],
    tasks: [
      {
        id: 'change-password',
        title: 'Change your password',
        status: 'IMPLEMENTED',
        purpose: 'Replace your password.',
        who: 'Everyone (not the break-glass account).',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Your name → Change password.', 'Current password, then the new one (12–72 characters).', 'Save.'],
        result: 'Changed; audited.',
        approval: 'None.',
        next: '—',
        related: ['getting-started'],
        keywords: ['change password', 'new password'],
      },
      {
        id: 'two-factor',
        title: 'Set up two-factor sign-in',
        status: 'IMPLEMENTED',
        purpose: 'Protect your account with a code from your phone.',
        who: 'Everyone may; Supervisor, HR Admin and System Admin must.',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Two-factor sign-in → Set up an authenticator app (required roles are taken there at sign-in).', 'Scan the QR code with Microsoft or Google Authenticator; name it clearly.', 'Type the 6-digit code to confirm.', 'Write down the 10 recovery codes shown once.'],
        result: 'Every sign-in asks for a code. New recovery codes replace the old ones; turning it off is possible only where your role does not require it.',
        approval: 'None.',
        next: '—',
        problems: [{ problem: 'Lost phone', fix: 'Sign in with a recovery code and set up the new phone, or ask HR to Reset two-factor.' }],
        related: ['administration'],
        keywords: ['two factor', '2fa', 'mfa', 'authenticator', 'recovery codes', 'lost phone'],
      },
      {
        id: 'sign-in-email',
        title: 'Change your sign-in e-mail',
        status: 'IMPLEMENTED',
        purpose: 'Sign in with a different e-mail address.',
        who: 'Everyone (not break-glass). HR can start it for you from Accounts.',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Two-factor sign-in → Sign-in e-mail → Change e-mail.', 'The new address and your current password.', 'Open the link sent to the new address within 30 minutes.'],
        result: 'After confirmation you sign in with the new address and all sessions are signed out. Until then nothing changes; Cancel the change stops it.',
        approval: 'None.',
        next: '—',
        related: [],
        keywords: ['change email', 'sign-in email'],
      },
      {
        id: 'telegram',
        title: 'Connect Telegram',
        status: 'PARTIAL',
        statusNote: 'Telegram is simulated in the demonstration system until the hospital\'s bot is set up.',
        purpose: 'Get a short Telegram message when a notification is waiting (never the details).',
        who: 'Everyone.',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Two-factor sign-in → Telegram → Connect Telegram.', 'Follow the link or scan the QR code in Telegram.'],
        result: 'Telegram shows as connected; you can disconnect at any time.',
        approval: 'None.',
        next: '—',
        related: ['notifications'],
        keywords: ['telegram'],
      },
      {
        id: 'sessions',
        title: 'Check your sign-in history',
        status: 'IMPLEMENTED',
        purpose: 'Spot a sign-in that was not you.',
        who: 'Everyone, own sessions only.',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Your name → Sign-in history.', 'Read sign-in time, last active, address, browser and status ("This session", Active, Ended).'],
        result: 'Read only.',
        approval: 'None.',
        next: 'A session you do not recognise: change your password and tell your administrator.',
        related: [],
        keywords: ['sessions', 'sign-in history', 'suspicious login'],
      },
    ],
    keywords: ['security', 'account', 'password'],
  },
];
