import type { GuideSection } from '../types';

export const START: GuideSection[] = [
  {
    id: 'getting-started',
    title: 'Getting started',
    summary: 'The AIGH Nursing Workforce system keeps one record of every nurse — contract, credentials and eligibility — and lets supervisors build rosters only from nurses who are allowed to work. Every screen shows data the server has checked; every change is recorded in the audit trail.',
    audience: 'Everyone',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    where: 'Open the hospital address in Chrome, Edge or Firefox and sign in.',
    flows: ['sign-in'],
    callouts: [
      { kind: 'info', text: 'What you see depends on your role and scope. A menu item or button that is missing is not an error: your account has no right to it. Ask HR if you need it.' },
      { kind: 'warning', text: 'Never share your password, recovery codes or the two-factor codes from your phone. Every action is recorded under the account that did it.' },
    ],
    tables: [
      {
        title: 'The side menu',
        columns: ['Menu item', 'What it is for', 'Who sees it'],
        rows: [
          ['Dashboard', 'Welcome and system status', 'Everyone'],
          ['Nurses', 'Staff master records, onboarding, login invitations', 'HR Admin, System Admin, Supervisor'],
          ['Contracts', 'Employment contracts and their approval', 'Everyone (employees see their own)'],
          ['Credentials', 'Licences and certificates, review queue, requirements, catalogue', 'HR Admin, System Admin, Supervisor'],
          ['My Profile', 'Your own record and phone numbers', 'Accounts linked to an employee'],
          ['My data', 'Your personal-data requests (PDPL)', 'Accounts linked to an employee'],
          ['My Credentials', 'Your own credentials, renewals and eligibility', 'Accounts linked to an employee'],
          ['Eligibility', 'Who may work today and why; emergency waivers', 'HR Admin, System Admin, Supervisor'],
          ['Workforce', 'Units, beds, departments, positions, coverage targets', 'Everyone (changes: HR / System Admin)'],
          ['Nursing KPIs', 'Nurse-to-bed indicators', 'HR Admin, System Admin, Supervisor'],
          ['Roster & Scheduling', 'The roster board; employees see their own shifts', 'Everyone (drafting: Supervisor)'],
          ['Attendance', 'Planned versus actual (clock-ins)', 'Everyone (employees see their own)'],
          ['Notifications', 'Your notices — the bell at the top shows how many are unread', 'Everyone'],
          ['Audit & Compliance', 'Audit trail and request log', 'System Admin'],
          ['Sign-in history', 'Your own sessions', 'Everyone'],
          ['Two-factor sign-in', 'Authenticator, recovery codes, sign-in e-mail, Telegram', 'Everyone'],
          ['Nursing Administration', 'Accounts, roles, approvals, data protection and system tools', 'HR Admin, System Admin'],
          ['Guidelines', 'This guide', 'Everyone'],
        ],
      },
      {
        title: 'The top bar',
        columns: ['Control', 'What it does'],
        rows: [
          ['☰', 'Folds or unfolds the side menu'],
          ['Bell', 'Opens Notifications; the number is how many are unread'],
          ['Moon / bulb', 'Switches dark or light mode (remembered on this browser)'],
          ['ع / EN', 'Switches Arabic or English; the layout turns right-to-left in Arabic'],
          ['Your name', 'Your roles, Change password, Sign-in history, Two-factor sign-in, Sign out'],
          ['Orange "Elevated until …"', 'A System Admin\'s temporary rights are on (see Security)'],
        ],
      },
    ],
    tasks: [
      {
        id: 'sign-in',
        title: 'Sign in',
        status: 'IMPLEMENTED',
        purpose: 'Open your account securely.',
        who: 'Everyone with an account.',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['Your sign-in e-mail and password (from HR, or chosen through an invitation link).', 'For Supervisor, HR Admin and System Admin: a phone with an authenticator app (Microsoft or Google Authenticator).'],
        steps: [
          'Open the website. Check the padlock in the address bar; never continue past a certificate warning.',
          'Enter your e-mail and password and click Sign in.',
          'If asked, type the 6-digit code from your authenticator app. If your role requires two-factor sign-in and it is not set up yet, the set-up screen opens first (see Security).',
          'The side menu shows the pages your role can use.',
        ],
        result: 'You are signed in. The session is listed under Sign-in history.',
        approval: 'None.',
        next: 'Start from the page for your task, or search this guide.',
        problems: [
          { problem: '"Invalid email or password"', fix: 'Check Caps Lock and the address. After 5 wrong attempts on one account within 15 minutes the account is paused for up to 15 minutes; after 20 failed attempts from one network, everyone on that network is paused. Stop guessing and use Forgot password?.' },
          { problem: 'The code is refused', fix: 'Use the current code (they change every 30 seconds and each works once), or sign in with a recovery code.' },
        ],
        related: ['security'],
        flow: 'sign-in',
        keywords: ['login', 'log in', 'password', 'two-factor', 'code'],
      },
      {
        id: 'forgot-password',
        title: 'Forgotten password',
        status: 'IMPLEMENTED',
        purpose: 'Choose a new password when you cannot sign in.',
        who: 'Staff accounts (no Supervisor, HR or administrator role) reset their own. Supervisor, HR and administrator accounts are reset by HR.',
        roles: ['EMPLOYEE'],
        before: ['Access to the mailbox of your sign-in e-mail.', 'E-mail must be switched on by the hospital.'],
        steps: ['On the sign-in page click Forgot password?.', 'Enter the e-mail address of your account and click Send link.', 'Open the link in the e-mail within 30 minutes.', 'Enter the new password twice (12 to 72 characters) and save.'],
        result: 'The password changes and every session of the account is signed out.',
        approval: 'None. For any account, HR can send a reset link (valid 24 hours) from Nursing Administration → Accounts → Send reset link, after confirming who is asking.',
        next: 'Sign in with the new password.',
        problems: [
          { problem: 'No e-mail arrives', fix: 'Check the spam folder. Supervisor, HR and administrator accounts never receive a self-service link: ask HR. If e-mail is not switched on, HR helps you instead.' },
        ],
        related: ['security', 'administration'],
        flow: 'password-reset',
        keywords: ['reset', 'forgot', 'lost password'],
      },
      {
        id: 'claim-account',
        title: 'Create your account from an invitation',
        status: 'IMPLEMENTED',
        purpose: 'Activate your own login from the private link HR sent you.',
        who: 'An employee who received an invitation e-mail.',
        roles: ['EMPLOYEE'],
        before: ['The invitation e-mail (the link works once and for 72 hours).', 'Your Job Number.'],
        steps: ['Open the link in the e-mail.', 'Enter your Job Number and continue.', 'Check the name, unit and position shown are yours (if not, stop and tell HR).', 'Enter a password of 12 to 72 characters twice and create the account.'],
        result: 'Your account is created and linked to your staff record. A newer invitation cancels the older link.',
        approval: 'None.',
        next: 'Sign in. Check My Profile and My Credentials.',
        problems: [{ problem: 'The link says it is invalid or expired', fix: 'Ask HR to send a new invitation.' }],
        related: ['nurses', 'self-service'],
        flow: 'invitation',
        keywords: ['invite', 'claim', 'register', 'first login'],
      },
    ],
    keywords: ['menu', 'start', 'overview', 'how to use'],
  },
  {
    id: 'roles',
    title: 'Roles and permissions',
    summary: 'Every account has the Employee view of its own records. HR gives extra roles — Supervisor, HR Admin, System Admin — each limited to a scope: some units, a department, or the whole hospital. The menu and buttons follow your roles, but the server checks every request on its own.',
    audience: 'Everyone',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    where: 'Your roles are listed under your name at the top right. The full table is in Nursing Administration → Access matrix.',
    tables: [
      {
        title: 'What each role is for',
        columns: ['Role', 'Scope', 'Sees', 'Changes'],
        rows: [
          ['Employee (every account linked to a staff record)', 'Own records', 'Own profile, contract, credentials, eligibility, shifts, clock-ins, notifications', 'Own phone numbers, own credentials and renewals, own personal-data requests'],
          ['Supervisor', 'Assigned units', 'Nurses, contracts (reduced), credentials (compliance view, no documents), eligibility, KPI, attendance of those units', 'Rosters of those units; emergency waivers'],
          ['HR Admin', 'Units, a department or hospital-wide', 'Everything about staff in scope', 'Staff records, contracts, credential decisions, requirements, accounts and roles in scope; hospital-wide HR also the catalogue and organisation'],
          ['System Admin', 'Hospital-wide, dormant until elevated', 'Audit, background jobs, system tools; HR screens while elevated', 'System configuration while elevated (1–4 hours, with a reason)'],
        ],
      },
      {
        title: 'Why something is missing or refused',
        columns: ['You see', 'Usually because'],
        rows: [
          ['A menu item is missing', 'Your role does not include that page (for example Audit & Compliance is System Admin only).'],
          ['Nursing Administration shows only some tabs', 'HR Admin does not see System Admin tabs; a System Admin who has not elevated sees only the tools tabs.'],
          ['A nurse is not in your list', 'The nurse is outside your scope (another unit or department), or the record was deleted.'],
          ['A button is missing on a row', 'The action does not apply to that record\'s status, or it is your own record (nobody approves or reviews their own).'],
          ['"Waiting for another administrator"', 'You asked for a protected change: a different administrator must approve it (see Approvals).'],
          ['An error naming SCOPE, SELF or APPROVAL', 'The server refused the action under the rules above. Read the message; it says which rule.'],
        ],
      },
    ],
    callouts: [
      { kind: 'info', text: 'A job title or position never gives a role: a Head Nurse is a Supervisor only if HR grants the Supervisor role.' },
      { kind: 'info', text: 'Two-factor sign-in is required for Supervisor, HR Admin and System Admin.' },
    ],
    tasks: [],
    keywords: ['permission', 'access', 'role', 'scope', 'cannot see', 'why can\'t i see', 'missing menu', 'disabled'],
  },
  {
    id: 'approvals',
    title: 'Approvals (four-eyes)',
    route: '/admin',
    summary: 'Some changes are too important for one person. They are saved as a request and take effect only when a different authorised administrator approves them in Nursing Administration → Approvals.',
    audience: 'HR Admin and System Admin',
    roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
    where: 'Nursing Administration → Approvals.',
    flows: ['four-eyes'],
    tables: [
      {
        title: 'What needs a second administrator',
        columns: ['Change', 'Where it is asked for', 'Who may approve'],
        rows: [
          ['Granting System Admin', 'Role assignments', 'Another administrator'],
          ['Granting HR Admin with hospital-wide scope', 'Role assignments', 'Another administrator'],
          ['New or changed credential type', 'Credentials → Catalog', 'Another hospital-wide administrator'],
          ['New or changed credential category', 'Credentials → Categories', 'Another hospital-wide administrator'],
          ['Hospital baseline import', 'Hospital baseline import', 'Another hospital-wide administrator'],
          ['Approving a contract', 'Contracts', 'An HR person who did not create or submit it (not through Approvals)'],
        ],
      },
    ],
    tasks: [
      {
        id: 'decide-request',
        title: 'Approve or reject a request',
        status: 'IMPLEMENTED',
        purpose: 'Apply, or turn down, a protected change another administrator asked for.',
        who: 'HR Admin or System Admin (elevated), other than the person who asked; within the request\'s scope.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        before: ['Read the description: it shows the change (before → after) and the requester\'s reason.'],
        steps: ['Open Nursing Administration → Approvals.', 'Find the Pending request.', 'Click Approve or Reject.', 'Write your reason (at least 5 characters) and confirm.'],
        result: 'Approve: the server checks the change again and applies it as you, in one step. Reject: nothing changes. Both are audited.',
        approval: 'This is the approval.',
        next: 'The requester sees the new status. For a role grant, the person can sign in with the new role.',
        problems: [
          { problem: 'No Approve button, only "Your request — waiting for another administrator"', fix: 'You asked for it. Someone else must decide, or you can Withdraw it.' },
          { problem: 'Approval refused because the item changed', fix: 'The record changed after the request; ask the requester to submit a new one.' },
        ],
        related: ['administration', 'credentials'],
        flow: 'four-eyes',
        keywords: ['approve', 'approval', 'reject', 'four eyes', 'second administrator', 'pending'],
      },
      {
        id: 'withdraw-request',
        title: 'Withdraw your own request',
        status: 'IMPLEMENTED',
        purpose: 'Cancel a protected change you asked for while it is still pending.',
        who: 'The administrator who submitted it.',
        roles: ['HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Nursing Administration → Approvals.', 'On your Pending request click Withdraw.', 'Give a reason (at least 5 characters).'],
        result: 'The request is Withdrawn; nothing is applied. Audited.',
        approval: 'None.',
        next: 'Submit a corrected request if needed.',
        related: ['administration'],
        keywords: ['cancel request', 'withdraw'],
      },
    ],
    keywords: ['approval', 'four-eyes', 'second approver'],
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    route: '/',
    summary: 'The first page after sign-in: a welcome line and whether the system (API) and its database are up.',
    audience: 'Everyone',
    roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
    callouts: [{ kind: 'info', text: 'Workforce figures (staffing, eligibility, expiring credentials) are not on the dashboard yet. Use Eligibility, Credentials, Nursing KPIs and Notifications for them.' }],
    tasks: [
      {
        id: 'read-dashboard',
        title: 'Check that the system is working',
        status: 'PARTIAL',
        statusNote: 'Shows system status only; workforce figures are planned.',
        purpose: 'See at a glance whether the application and its database answer.',
        who: 'Everyone.',
        roles: ['EMPLOYEE', 'SUPERVISOR', 'HR_ADMIN', 'SYSTEM_ADMIN'],
        steps: ['Open Dashboard.', 'API status and Database status should both be green ("Up").'],
        result: 'Nothing is changed.',
        approval: 'None.',
        next: 'If either is red, tell the system administrator; other pages will not load data.',
        related: ['troubleshooting'],
        keywords: ['status', 'home', 'up', 'down'],
      },
    ],
  },
];
